/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brotherssoft.samodconstructions.view;

import com.brotherssoft.samodconstructions.controller.R_BankController;
import com.brotherssoft.samodconstructions.controller.R_BranchController;
import com.brotherssoft.samodconstructions.custom.IDGenerator;
import com.brotherssoft.samodconstructions.model.R_Bank;
import com.brotherssoft.samodconstructions.model.R_Branch;
import com.brotherssoft.samodconstructions.serverconnector.ServerConnector;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akvasoft
 */
public class Bank_Panel extends javax.swing.JPanel {

    DefaultTableModel dtmBank;
    DefaultTableModel dtmBranch;
    R_BankController bankController;
    R_BranchController branchController;

    /**
     * Creates new form Brance_Panel
     */
    public Bank_Panel(int x) throws Exception {
        initComponents();
        dtmBank = (DefaultTableModel) tbl_bank.getModel();
        dtmBranch = (DefaultTableModel) tbl_branch.getModel();
        bankController = ServerConnector.getServerConnetor().getBankController();
        branchController = ServerConnector.getServerConnetor().getBranchController();
        showPanel(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Branch_panel = new javax.swing.JPanel();
        bank_panel_hedding1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_Input_Panel_Branch = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtBranchName = new javax.swing.JTextField();
        txtBranchCode = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        taBranchDesc = new javax.swing.JTextArea();
        btn_save_branch = new javax.swing.JButton();
        cmbBank = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtBranchAddress = new javax.swing.JTextField();
        cmbBranchStates = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        btn_back_to_bank = new javax.swing.JButton();
        btn_remove_branch1 = new javax.swing.JButton();
        btn_new_branch = new javax.swing.JButton();
        tbl_panel_Branch = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_branch = new javax.swing.JTable();
        txt_branch_search = new javax.swing.JTextField();
        Bank_panel = new javax.swing.JPanel();
        bank_panel_hedding = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        bank_panel_input_area = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_bank_name = new javax.swing.JTextField();
        txt_bank_code = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bank_desc = new javax.swing.JTextArea();
        btn_bank_save = new javax.swing.JButton();
        cmb_bank_states = new javax.swing.JComboBox<>();
        btn_branch = new javax.swing.JButton();
        lbl_bnakId = new javax.swing.JLabel();
        btn_bank_new = new javax.swing.JButton();
        btn_bank_remove = new javax.swing.JButton();
        bank_panel_tbl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bank = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();

        Branch_panel.setBackground(new java.awt.Color(255, 255, 255));
        Branch_panel.setPreferredSize(new java.awt.Dimension(1050, 710));

        bank_panel_hedding1.setBackground(new java.awt.Color(122, 72, 222));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Administrations / System Management / Master Detail /");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Branch Manager");

        javax.swing.GroupLayout bank_panel_hedding1Layout = new javax.swing.GroupLayout(bank_panel_hedding1);
        bank_panel_hedding1.setLayout(bank_panel_hedding1Layout);
        bank_panel_hedding1Layout.setHorizontalGroup(
            bank_panel_hedding1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_hedding1Layout.createSequentialGroup()
                .addGroup(bank_panel_hedding1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bank_panel_hedding1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bank_panel_hedding1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bank_panel_hedding1Layout.setVerticalGroup(
            bank_panel_hedding1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_hedding1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bank_panel_hedding1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        txt_Input_Panel_Branch.setBackground(new java.awt.Color(255, 255, 255));
        txt_Input_Panel_Branch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save And Modify Branch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("Branch Name");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("Branch Code");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setText("Bank");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setText("Description");

        txtBranchName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtBranchCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        taBranchDesc.setColumns(20);
        taBranchDesc.setRows(5);
        jScrollPane4.setViewportView(taBranchDesc);

        btn_save_branch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_save_branch.setText("Save");
        btn_save_branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_branchActionPerformed(evt);
            }
        });

        cmbBank.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Bank -" }));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setText("Branch Address");

        txtBranchAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        cmbBranchStates.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbBranchStates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel18.setText("States");

        btn_back_to_bank.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_back_to_bank.setText("Bank");
        btn_back_to_bank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_back_to_bankMouseClicked(evt);
            }
        });

        btn_remove_branch1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_remove_branch1.setText("Remove");
        btn_remove_branch1.setEnabled(false);
        btn_remove_branch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove_branch1ActionPerformed(evt);
            }
        });

        btn_new_branch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_new_branch.setText("New");
        btn_new_branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new_branchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txt_Input_Panel_BranchLayout = new javax.swing.GroupLayout(txt_Input_Panel_Branch);
        txt_Input_Panel_Branch.setLayout(txt_Input_Panel_BranchLayout);
        txt_Input_Panel_BranchLayout.setHorizontalGroup(
            txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_Input_Panel_BranchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txt_Input_Panel_BranchLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBranchName))
                    .addGroup(txt_Input_Panel_BranchLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                    .addGroup(txt_Input_Panel_BranchLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBank, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(txt_Input_Panel_BranchLayout.createSequentialGroup()
                        .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBranchAddress)
                            .addComponent(txtBranchCode)))
                    .addGroup(txt_Input_Panel_BranchLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBranchStates, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_BranchLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_new_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_remove_branch1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_back_to_bank, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        txt_Input_Panel_BranchLayout.setVerticalGroup(
            txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_Input_Panel_BranchLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBranchCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBranchAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBranchStates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txt_Input_Panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_remove_branch1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_new_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back_to_bank, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_panel_Branch.setBackground(new java.awt.Color(255, 255, 255));
        tbl_panel_Branch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Branch Infomations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        tbl_branch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbl_branch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bank Name", "Branch Code", "Branch Name", "States"
            }
        ));
        tbl_branch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_branch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_branchMouseClicked(evt);
            }
        });
        tbl_branch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_branchKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_branch);

        txt_branch_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_branch_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_branch_search.setText("Search");
        txt_branch_search.setToolTipText("Use Bank Nname To Search !");

        javax.swing.GroupLayout tbl_panel_BranchLayout = new javax.swing.GroupLayout(tbl_panel_Branch);
        tbl_panel_Branch.setLayout(tbl_panel_BranchLayout);
        tbl_panel_BranchLayout.setHorizontalGroup(
            tbl_panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbl_panel_BranchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_branch_search, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tbl_panel_BranchLayout.setVerticalGroup(
            tbl_panel_BranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbl_panel_BranchLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(txt_branch_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout Branch_panelLayout = new javax.swing.GroupLayout(Branch_panel);
        Branch_panel.setLayout(Branch_panelLayout);
        Branch_panelLayout.setHorizontalGroup(
            Branch_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Branch_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Input_Panel_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbl_panel_Branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(bank_panel_hedding1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Branch_panelLayout.setVerticalGroup(
            Branch_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Branch_panelLayout.createSequentialGroup()
                .addComponent(bank_panel_hedding1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(Branch_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Input_Panel_Branch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl_panel_Branch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Bank_panel.setBackground(new java.awt.Color(255, 255, 255));
        Bank_panel.setPreferredSize(new java.awt.Dimension(1050, 710));

        bank_panel_hedding.setBackground(new java.awt.Color(122, 72, 222));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Administrations / System Management / Master Detail /");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Bank Manager");

        javax.swing.GroupLayout bank_panel_heddingLayout = new javax.swing.GroupLayout(bank_panel_hedding);
        bank_panel_hedding.setLayout(bank_panel_heddingLayout);
        bank_panel_heddingLayout.setHorizontalGroup(
            bank_panel_heddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_heddingLayout.createSequentialGroup()
                .addGroup(bank_panel_heddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bank_panel_heddingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bank_panel_heddingLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bank_panel_heddingLayout.setVerticalGroup(
            bank_panel_heddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_heddingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bank_panel_heddingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        bank_panel_input_area.setBackground(new java.awt.Color(255, 255, 255));
        bank_panel_input_area.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save And Modify Bank", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Bank Name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Bank Code");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("States");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Description");

        txt_bank_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txt_bank_code.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        bank_desc.setColumns(20);
        bank_desc.setRows(5);
        jScrollPane1.setViewportView(bank_desc);

        btn_bank_save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_bank_save.setText("Save");
        btn_bank_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bank_saveActionPerformed(evt);
            }
        });

        cmb_bank_states.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_bank_states.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        btn_branch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_branch.setText("Branch");
        btn_branch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_branchMouseClicked(evt);
            }
        });

        lbl_bnakId.setText("jLabel2");
        lbl_bnakId.setEnabled(false);

        btn_bank_new.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_bank_new.setText("New");
        btn_bank_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bank_newActionPerformed(evt);
            }
        });

        btn_bank_remove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_bank_remove.setText("Remove");
        btn_bank_remove.setEnabled(false);
        btn_bank_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bank_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bank_panel_input_areaLayout = new javax.swing.GroupLayout(bank_panel_input_area);
        bank_panel_input_area.setLayout(bank_panel_input_areaLayout);
        bank_panel_input_areaLayout.setHorizontalGroup(
            bank_panel_input_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_input_areaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_bnakId)
                .addContainerGap(424, Short.MAX_VALUE))
            .addGroup(bank_panel_input_areaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bank_panel_input_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bank_panel_input_areaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bank_name))
                    .addGroup(bank_panel_input_areaLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                    .addGroup(bank_panel_input_areaLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bank_code))
                    .addGroup(bank_panel_input_areaLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_bank_states, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_input_areaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_bank_new, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_bank_save, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_bank_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bank_panel_input_areaLayout.setVerticalGroup(
            bank_panel_input_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_input_areaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(bank_panel_input_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bank_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bank_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_bank_states))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bank_new, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bank_save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bank_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_bnakId)
                .addGap(54, 54, 54))
        );

        bank_panel_tbl.setBackground(new java.awt.Color(255, 255, 255));
        bank_panel_tbl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank Infomations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        tbl_bank.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbl_bank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bank Name", "Bank Code", "States", "Description"
            }
        ));
        tbl_bank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_bank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bankMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_bank);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Search");
        jTextField4.setToolTipText("Use Bank Nname To Search !");

        javax.swing.GroupLayout bank_panel_tblLayout = new javax.swing.GroupLayout(bank_panel_tbl);
        bank_panel_tbl.setLayout(bank_panel_tblLayout);
        bank_panel_tblLayout.setHorizontalGroup(
            bank_panel_tblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_tblLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bank_panel_tblLayout.setVerticalGroup(
            bank_panel_tblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_tblLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout Bank_panelLayout = new javax.swing.GroupLayout(Bank_panel);
        Bank_panel.setLayout(Bank_panelLayout);
        Bank_panelLayout.setHorizontalGroup(
            Bank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bank_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bank_panel_input_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bank_panel_tbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(bank_panel_hedding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Bank_panelLayout.setVerticalGroup(
            Bank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bank_panelLayout.createSequentialGroup()
                .addComponent(bank_panel_hedding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(Bank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bank_panel_input_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bank_panel_tbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(Branch_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Bank_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Branch_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Bank_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Branch_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Bank_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back_to_bankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_back_to_bankMouseClicked
        Branch_panel.setVisible(false);
        Bank_panel.setVisible(true);
    }//GEN-LAST:event_btn_back_to_bankMouseClicked

    private void btn_branchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_branchMouseClicked
        Bank_panel.setVisible(false);
        Branch_panel.setVisible(true);
    }//GEN-LAST:event_btn_branchMouseClicked

    private void btn_bank_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bank_saveActionPerformed
        if (btn_bank_save.getText().equalsIgnoreCase("Save")) {
            saveBankDetails();
        } else {
            updateBankDetails();
        }
        loadBankTable();


    }//GEN-LAST:event_btn_bank_saveActionPerformed

    private void tbl_bankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bankMouseClicked
        loadFromTableRow();
    }//GEN-LAST:event_tbl_bankMouseClicked

    private void btn_bank_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bank_newActionPerformed
        txt_bank_name.setText("");
        txt_bank_code.setText("");
        cmb_bank_states.setSelectedIndex(0);
        bank_desc.setText("");

        btn_bank_save.setText("Save");
        btn_bank_remove.setEnabled(false);
    }//GEN-LAST:event_btn_bank_newActionPerformed

    private void btn_bank_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bank_removeActionPerformed
        removeBank();
    }//GEN-LAST:event_btn_bank_removeActionPerformed

    private void btn_save_branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_branchActionPerformed
        if(btn_save_branch.getText().equalsIgnoreCase("Save")){
            saveBranch();
        }else{
            updateBranch();
        }
    }//GEN-LAST:event_btn_save_branchActionPerformed

    private void tbl_branchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_branchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_branchKeyPressed

    private void tbl_branchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_branchMouseClicked
        loadFromBranchTable();
    }//GEN-LAST:event_tbl_branchMouseClicked

    private void btn_remove_branch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove_branch1ActionPerformed
        deleteBranch();
    }//GEN-LAST:event_btn_remove_branch1ActionPerformed

    private void btn_new_branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new_branchActionPerformed
        
        txtBranchName.setText("");
        txtBranchCode.setText("");
        txtBranchAddress.setText("");
        cmbBank.setSelectedIndex(0);
        cmbBranchStates.setSelectedIndex(0);
        taBranchDesc.setText("");
        
        btn_remove_branch1.setEnabled(false);
        btn_save_branch.setText("Save");
        
    }//GEN-LAST:event_btn_new_branchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bank_panel;
    private javax.swing.JPanel Branch_panel;
    private javax.swing.JTextArea bank_desc;
    private javax.swing.JPanel bank_panel_hedding;
    private javax.swing.JPanel bank_panel_hedding1;
    private javax.swing.JPanel bank_panel_input_area;
    private javax.swing.JPanel bank_panel_tbl;
    private javax.swing.JButton btn_back_to_bank;
    private javax.swing.JButton btn_bank_new;
    private javax.swing.JButton btn_bank_remove;
    private javax.swing.JButton btn_bank_save;
    private javax.swing.JButton btn_branch;
    private javax.swing.JButton btn_new_branch;
    private javax.swing.JButton btn_remove_branch1;
    private javax.swing.JButton btn_save_branch;
    private javax.swing.JComboBox<String> cmbBank;
    private javax.swing.JComboBox<String> cmbBranchStates;
    private javax.swing.JComboBox<String> cmb_bank_states;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbl_bnakId;
    private javax.swing.JTextArea taBranchDesc;
    private javax.swing.JTable tbl_bank;
    private javax.swing.JTable tbl_branch;
    private javax.swing.JPanel tbl_panel_Branch;
    private javax.swing.JTextField txtBranchAddress;
    private javax.swing.JTextField txtBranchCode;
    private javax.swing.JTextField txtBranchName;
    private javax.swing.JPanel txt_Input_Panel_Branch;
    private javax.swing.JTextField txt_bank_code;
    private javax.swing.JTextField txt_bank_name;
    private javax.swing.JTextField txt_branch_search;
    // End of variables declaration//GEN-END:variables

    private void showPanel(int x) {
        if (x == 1) {

            Branch_panel.setVisible(true);
            Bank_panel.setVisible(false);
            loadToBankCombo();
            loadBranchTable();
        } else if (x == 2) {

            Branch_panel.setVisible(false);
            Bank_panel.setVisible(true);
            loadBankTable();
        }
    }

    private void saveBankDetails() {
        try {
            int bank_id = IDGenerator.getNewID("r_bank", "BANK_ID");
            String bank_name = txt_bank_name.getText();
            String bank_code = txt_bank_code.getText();
            String brach_desc = bank_desc.getText();
            String bank_status = Integer.toString(cmb_bank_states.getSelectedIndex());

            R_Bank bank = new R_Bank(bank_id, bank_name, bank_code, brach_desc, bank_status);

            boolean addBank = bankController.addBank(bank);

            if (addBank) {
                JOptionPane.showMessageDialog(this, "Bank Added Successfully...");
            } else {
                JOptionPane.showMessageDialog(this, "Bank Adding Failed...");
            }

        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadBankTable() {
        System.out.println("tablee run wenooo...");
        try {
            dtmBank.setRowCount(0);
            List<R_Bank> allBanks = bankController.getAllBanks();
            for (R_Bank allBank : allBanks) {

                String bankStatus = "";
                if (allBank.getBank_status().equalsIgnoreCase("0")) {
                    bankStatus = "Active";
                } else {
                    bankStatus = "Inactive";
                }

                String[] rowDataBank = {allBank.getBank_name(), allBank.getBank_code(), bankStatus, allBank.getBank_description()};
                System.out.println("////////" + allBank.getBank_name());
                dtmBank.addRow(rowDataBank);
            }

        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadFromTableRow() {
        try {

            int selectedRow = tbl_bank.getSelectedRow();

            R_Bank searchBank = searchBankByTableName();

            txt_bank_name.setText(searchBank.getBank_name());
            txt_bank_code.setText(searchBank.getBank_code());
            bank_desc.setText(searchBank.getBank_description());
            cmb_bank_states.setSelectedIndex(Integer.parseInt(searchBank.getBank_status()));
            lbl_bnakId.setText(Integer.toString(searchBank.getBank_id()));

            btn_bank_save.setText("Update");
            btn_bank_remove.setEnabled(true);

        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateBankDetails() {
        System.out.println("Update ekata yaii...");
        try {

            int bankId = searchBankByTableName().getBank_id();
//            System.out.println("////////////////"+searchBank.getBank_id());
            String bank_name = txt_bank_name.getText();
            String bank_code = txt_bank_code.getText();
            String brach_desc = bank_desc.getText();
            String bank_status = Integer.toString(cmb_bank_states.getSelectedIndex());

            R_Bank bank1 = new R_Bank(bankId, bank_name, bank_code, brach_desc, bank_status);

            boolean updateBank = bankController.updateBank(bank1);
            if (updateBank) {
                JOptionPane.showMessageDialog(this, "Bank Updated Successfully...");
            } else {
                JOptionPane.showMessageDialog(this, "Bank Updating Failed...");
            }
        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private R_Bank searchBankByTableName() {
        R_Bank searchBank = null;
        try {
            int selectedRow = tbl_bank.getSelectedRow();
            searchBank = bankController.searchBankByName(dtmBank.getValueAt(selectedRow, 0).toString());
        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return searchBank;
    }

    private void removeBank() {
        try {
            int bank_id = searchBankByTableName().getBank_id();
            boolean deleteBank = bankController.deleteBank(bank_id);
            if (deleteBank) {
                JOptionPane.showMessageDialog(this, "Bank is Deleted Successfully...");
            } else {
                JOptionPane.showMessageDialog(this, "Deleting Bank Failed..");
            }
        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

        txt_bank_name.setText("");
        txt_bank_code.setText("");
        cmb_bank_states.setSelectedIndex(0);
        bank_desc.setText("");

        loadBankTable();
    }

    private void loadToBankCombo() {
        try {
            List<R_Bank> allBanks = bankController.getAllBanks();
            cmbBank.removeAll();
            for (R_Bank allBank : allBanks) {
                cmbBank.addItem(allBank.getBank_name());
            }
        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveBranch() {

        try {

            int branch_id = IDGenerator.getNewID("r_branch", "BRANCH_ID");
            R_Bank searchBankByName = bankController.searchBankByName(cmbBank.getSelectedItem().toString());
            int branch_bank_id = searchBankByName.getBank_id();
            String branchName = txtBranchName.getText();
            String branchCode = txtBranchCode.getText();
            String branchDesc = taBranchDesc.getText();
            String branchAddress = txtBranchAddress.getText();
            int branchStatus = cmbBranchStates.getSelectedIndex();

            R_Branch branch = new R_Branch(branch_id, branch_bank_id, branchName, branchCode, branchDesc, branchAddress, branchStatus);

            boolean addBranch = branchController.addBranch(branch);
            if (addBranch) {
                JOptionPane.showMessageDialog(this, "Branch Saved Successfully..");
            } else {
                JOptionPane.showMessageDialog(this, "Branch Saving went wrong..");
            }

        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadBranchTable();

    }

    private void loadBranchTable() {

        try {

            dtmBranch.setRowCount(0);
            List<R_Branch> allBranches = branchController.getAllBranches();
            for (R_Branch allBranche : allBranches) {
                R_Bank searchBank = bankController.searchBank(allBranche.getBranch_bank_id());
                String branchStatus = "";
                if (allBranche.getBranch_status() == 0) {
                    branchStatus = "Avtive";
                } else {
                    branchStatus = "Inactive";
                }
                String rowData[] = {searchBank.getBank_name(), allBranche.getBranch_code(), allBranche.getBranch_name(), branchStatus};
                dtmBranch.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadFromBranchTable() {
        try {

            R_Branch branch = searchBranchBytableCode();
            txtBranchName.setText(branch.getBranch_name());
            txtBranchCode.setText(branch.getBranch_code());
            txtBranchAddress.setText(branch.getBranch_address());
            R_Bank searchBank = bankController.searchBank(branch.getBranch_bank_id());
            cmbBank.setSelectedItem(searchBank.getBank_name());
            cmbBranchStates.setSelectedIndex(branch.getBranch_status());
            taBranchDesc.setText(branch.getBranch_description());

        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

        btn_save_branch.setText("Update");
        btn_remove_branch1.setEnabled(true);

    }

    private R_Branch searchBranchBytableCode() {
        R_Branch searchBranchByCode = null;
        try {
            int selectedRow = tbl_branch.getSelectedRow();
            searchBranchByCode = branchController.searchBranchByCode(dtmBranch.getValueAt(selectedRow, 1).toString());
        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return searchBranchByCode;
    }

    private void updateBranch() {
        
        try {
            
            int branch_id = searchBranchBytableCode().getBranch_id();
            int bank_id = bankController.searchBankByName(cmbBank.getSelectedItem().toString()).getBank_id();
            String branchName = txtBranchName.getText();
            String branchCode = txtBranchCode.getText();
            String branchDesc = taBranchDesc.getText();
            String branchAddress = txtBranchAddress.getText();
            int branchStatus = cmbBranchStates.getSelectedIndex();
            
            R_Branch branchU = new R_Branch(branch_id, bank_id, branchName, branchCode, branchDesc, branchAddress, branchStatus);
            
            boolean updateBranch = branchController.updateBranch(branchU);
            if (updateBranch) {
                JOptionPane.showMessageDialog(this, "Branch Updated Successfully..");
            }else{
                JOptionPane.showMessageDialog(this, "Branch Updating Failed..");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        loadBranchTable();
    }

    private void deleteBranch() {
        
        int branch_id = searchBranchBytableCode().getBranch_id();
        try {
            boolean deleteBranch = branchController.deleteBranch(branch_id);
            if (deleteBranch) {
                JOptionPane.showMessageDialog(this, "Selected Branch Removed From Records..");
            }else{
                JOptionPane.showMessageDialog(this, "Removing Brach occured error..");
            }
        } catch (Exception ex) {
            Logger.getLogger(Bank_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        loadBranchTable();
    }

}
