/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brotherssoft.samodconstructions.view;

import com.brotherssoft.samodconstructions.controller.M_EmployeeController;
import com.brotherssoft.samodconstructions.controller.R_BankController;
import com.brotherssoft.samodconstructions.controller.R_BranchController;
import com.brotherssoft.samodconstructions.controller.R_JobTypeController;
import com.brotherssoft.samodconstructions.controller.R_SalaryTypeController;
import com.brotherssoft.samodconstructions.custom.AmountFieldFormat;
import com.brotherssoft.samodconstructions.custom.Validation;
import com.brotherssoft.samodconstructions.model.M_Employee;
import com.brotherssoft.samodconstructions.model.R_Bank;
import com.brotherssoft.samodconstructions.model.R_Branch;
import com.brotherssoft.samodconstructions.model.R_JobType;
import com.brotherssoft.samodconstructions.model.R_SalaryType;
import com.brotherssoft.samodconstructions.serverconnector.ServerConnector;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akvasoft
 */
public class Employee_Salary extends javax.swing.JPanel {

    M_Employee employee = null;
    M_EmployeeController employeeController;
    R_BankController bankController;
    R_BranchController branchController;
    R_SalaryTypeController salaryTypeController;
    DefaultTableModel dtmEmpSalary;
    DecimalFormat decimalFormat;
    R_JobTypeController jobTypeController;

    AmountFieldFormat fieldFormat = new AmountFieldFormat();

    /**
     * Creates new form Employee_Salary
     */
    public Employee_Salary() throws Exception {
        initComponents();
        cmb_searchEmp_subContractor.setVisible(false);

        employeeController = ServerConnector.getServerConnetor().getEmployeeController();
        bankController = ServerConnector.getServerConnetor().getBankController();
        branchController = ServerConnector.getServerConnetor().getBranchController();
        salaryTypeController = ServerConnector.getServerConnetor().getSalaryTypeController();
        jobTypeController = ServerConnector.getServerConnetor().getJobTypeController();
        dtmEmpSalary = (DefaultTableModel) tb_emp_sal.getModel();

        decimalFormat = new DecimalFormat("#,##0.00");
        decimalFormat.setGroupingSize(3);

        loadBankCombo();
        loadSalTypeCombo();
        loadEmpSalTable();
        loadJobTypeCombo();

    }

    Employee_Salary(String text) throws Exception {
        initComponents();
        cmb_searchEmp_subContractor.setVisible(false);

        employeeController = ServerConnector.getServerConnetor().getEmployeeController();
        bankController = ServerConnector.getServerConnetor().getBankController();
        branchController = ServerConnector.getServerConnetor().getBranchController();
        salaryTypeController = ServerConnector.getServerConnetor().getSalaryTypeController();
        jobTypeController = ServerConnector.getServerConnetor().getJobTypeController();
        dtmEmpSalary = (DefaultTableModel) tb_emp_sal.getModel();
//        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
//        symbols.setGroupingSeparator(' ');
        decimalFormat = new DecimalFormat("#,##0.00");
        decimalFormat.setGroupingSize(3);

        loadBankCombo();
        loadSalTypeCombo();
        loadEmpSalTable();

        employee = employeeController.searchEmployeeByNIC(text);
        loadEmployeeData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Employee_Salary = new javax.swing.JPanel();
        bank_panel_hedding4 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txt_Input_Panel_Branch1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txt_employee = new javax.swing.JTextField();
        txt_emp_acc_no = new javax.swing.JTextField();
        btn_save_emp_salary = new javax.swing.JButton();
        btn_emp_salary_cancel = new javax.swing.JButton();
        cmbBankEmp_Salary = new javax.swing.JComboBox<>();
        cmbBranchEmp_salary = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cmbSalaryType = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        txt_emp_sal_basic = new javax.swing.JTextField();
        txt_emp_sal_al_1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_emp_al_2 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txt_emp_al_3 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txt_emp_al_4 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        cmbEPFStatus = new javax.swing.JComboBox<>();
        tbl_panel_Branch1 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tb_emp_sal = new javax.swing.JTable();
        txt_emp_sal_search = new javax.swing.JTextField();
        cmb_searchEmp_subContractor = new javax.swing.JComboBox<>();
        cmb_searchEmp_jobType = new javax.swing.JComboBox<>();

        Employee_Salary.setBackground(new java.awt.Color(255, 255, 255));
        Employee_Salary.setPreferredSize(new java.awt.Dimension(1050, 710));

        bank_panel_hedding4.setBackground(new java.awt.Color(122, 72, 222));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 255));
        jLabel35.setText("Administrations / System Management / Master Detail /");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("Employee Salary");

        javax.swing.GroupLayout bank_panel_hedding4Layout = new javax.swing.GroupLayout(bank_panel_hedding4);
        bank_panel_hedding4.setLayout(bank_panel_hedding4Layout);
        bank_panel_hedding4Layout.setHorizontalGroup(
            bank_panel_hedding4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_hedding4Layout.createSequentialGroup()
                .addGroup(bank_panel_hedding4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bank_panel_hedding4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bank_panel_hedding4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        bank_panel_hedding4Layout.setVerticalGroup(
            bank_panel_hedding4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_hedding4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bank_panel_hedding4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        txt_Input_Panel_Branch1.setBackground(new java.awt.Color(255, 255, 255));
        txt_Input_Panel_Branch1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save And Modify Employee Salary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel37.setText("Employee Name");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel38.setText("Employee Account No");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel39.setText("Bank");

        txt_employee.setEditable(false);
        txt_employee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txt_emp_acc_no.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_emp_acc_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_acc_noActionPerformed(evt);
            }
        });

        btn_save_emp_salary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_save_emp_salary.setText("Save");
        btn_save_emp_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_emp_salaryActionPerformed(evt);
            }
        });

        btn_emp_salary_cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_emp_salary_cancel.setText("Cancel");
        btn_emp_salary_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emp_salary_cancelActionPerformed(evt);
            }
        });

        cmbBankEmp_Salary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBankEmp_Salary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Bank -" }));
        cmbBankEmp_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBankEmp_SalaryActionPerformed(evt);
            }
        });

        cmbBranchEmp_salary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBranchEmp_salary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Branch -" }));
        cmbBranchEmp_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBranchEmp_salaryActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel42.setText("Branch");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel43.setText("Salary Type");

        cmbSalaryType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbSalaryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Salary Type -" }));
        cmbSalaryType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalaryTypeActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel40.setText("Basic Salary");

        txt_emp_sal_basic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_emp_sal_basic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emp_sal_basicMouseClicked(evt);
            }
        });
        txt_emp_sal_basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_sal_basicActionPerformed(evt);
            }
        });
        txt_emp_sal_basic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emp_sal_basicKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emp_sal_basicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emp_sal_basicKeyTyped(evt);
            }
        });

        txt_emp_sal_al_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_emp_sal_al_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emp_sal_al_1MouseClicked(evt);
            }
        });
        txt_emp_sal_al_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_sal_al_1ActionPerformed(evt);
            }
        });
        txt_emp_sal_al_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emp_sal_al_1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emp_sal_al_1KeyReleased(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel41.setText("Allowance 1");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel44.setText("Allowance 2");

        txt_emp_al_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_emp_al_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emp_al_2MouseClicked(evt);
            }
        });
        txt_emp_al_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_al_2ActionPerformed(evt);
            }
        });
        txt_emp_al_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emp_al_2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emp_al_2KeyReleased(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel45.setText("Allowance 3");

        txt_emp_al_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_emp_al_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emp_al_3MouseClicked(evt);
            }
        });
        txt_emp_al_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_al_3ActionPerformed(evt);
            }
        });
        txt_emp_al_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emp_al_3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emp_al_3KeyReleased(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel46.setText("Allowance 4");

        txt_emp_al_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_emp_al_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emp_al_4MouseClicked(evt);
            }
        });
        txt_emp_al_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_al_4ActionPerformed(evt);
            }
        });
        txt_emp_al_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emp_al_4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emp_al_4KeyReleased(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel47.setText("EPF Granted");

        cmbEPFStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEPFStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbEPFStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEPFStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txt_Input_Panel_Branch1Layout = new javax.swing.GroupLayout(txt_Input_Panel_Branch1);
        txt_Input_Panel_Branch1.setLayout(txt_Input_Panel_Branch1Layout);
        txt_Input_Panel_Branch1Layout.setHorizontalGroup(
            txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_Input_Panel_Branch1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_employee))
                    .addGroup(txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBankEmp_Salary, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_emp_acc_no))
                    .addGroup(txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBranchEmp_salary, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSalaryType, 0, 288, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_emp_sal_basic))
                    .addGroup(txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_emp_sal_al_1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_emp_al_2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_emp_al_3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_emp_al_4))
                    .addGroup(txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEPFStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_save_emp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_emp_salary_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        txt_Input_Panel_Branch1Layout.setVerticalGroup(
            txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emp_acc_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBankEmp_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBranchEmp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSalaryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEPFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emp_sal_basic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emp_sal_al_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emp_al_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emp_al_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emp_al_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_Input_Panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_emp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_emp_salary_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbl_panel_Branch1.setBackground(new java.awt.Color(255, 255, 255));
        tbl_panel_Branch1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Infomations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        tb_emp_sal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tb_emp_sal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Initials", "First Name", "Middle Name", "Last Name"
            }
        ));
        tb_emp_sal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tb_emp_sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_emp_salMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tb_emp_sal);

        txt_emp_sal_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_emp_sal_search.setForeground(new java.awt.Color(153, 153, 153));
        txt_emp_sal_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_emp_sal_search.setText("Search Employee");
        txt_emp_sal_search.setToolTipText("Use Bank Nname To Search !");
        txt_emp_sal_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emp_sal_searchMouseClicked(evt);
            }
        });
        txt_emp_sal_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_sal_searchActionPerformed(evt);
            }
        });
        txt_emp_sal_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emp_sal_searchKeyReleased(evt);
            }
        });

        cmb_searchEmp_subContractor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Sub Contractor -" }));
        cmb_searchEmp_subContractor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_searchEmp_subContractorActionPerformed(evt);
            }
        });

        cmb_searchEmp_jobType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Job Type -", "LOAD ALL" }));
        cmb_searchEmp_jobType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_searchEmp_jobTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbl_panel_Branch1Layout = new javax.swing.GroupLayout(tbl_panel_Branch1);
        tbl_panel_Branch1.setLayout(tbl_panel_Branch1Layout);
        tbl_panel_Branch1Layout.setHorizontalGroup(
            tbl_panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbl_panel_Branch1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbl_panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                    .addGroup(tbl_panel_Branch1Layout.createSequentialGroup()
                        .addComponent(cmb_searchEmp_jobType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_searchEmp_subContractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_emp_sal_search, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tbl_panel_Branch1Layout.setVerticalGroup(
            tbl_panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbl_panel_Branch1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tbl_panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbl_panel_Branch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_searchEmp_jobType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_searchEmp_subContractor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_emp_sal_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout Employee_SalaryLayout = new javax.swing.GroupLayout(Employee_Salary);
        Employee_Salary.setLayout(Employee_SalaryLayout);
        Employee_SalaryLayout.setHorizontalGroup(
            Employee_SalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_SalaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Input_Panel_Branch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbl_panel_Branch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(bank_panel_hedding4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Employee_SalaryLayout.setVerticalGroup(
            Employee_SalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_SalaryLayout.createSequentialGroup()
                .addComponent(bank_panel_hedding4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(Employee_SalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Input_Panel_Branch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbl_panel_Branch1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Employee_Salary, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Employee_Salary, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_emp_salMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_emp_salMouseClicked
        try {
            int selectedRow = tb_emp_sal.getSelectedRow();
            String initials = (String) dtmEmpSalary.getValueAt(selectedRow, 0);
            String fName = (String) dtmEmpSalary.getValueAt(selectedRow, 1);
            String mName = (String) dtmEmpSalary.getValueAt(selectedRow, 2);
            String lNAme = (String) dtmEmpSalary.getValueAt(selectedRow, 3);
            employee = employeeController.searchByFullName(fName, mName, lNAme);
            loadEmployeeData();

        } catch (Exception ex) {
            Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }

        btn_save_emp_salary.setText("Update");
        txt_emp_sal_search.setText("Search Employee");
        txt_emp_sal_search.setForeground(Color.GRAY);
    }//GEN-LAST:event_tb_emp_salMouseClicked

    private void cmbBankEmp_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBankEmp_SalaryActionPerformed
        if (cmbBankEmp_Salary.getSelectedIndex() != 0) {
            loadBranchCombo();
            cmbBranchEmp_salary.requestFocus();
        }

    }//GEN-LAST:event_cmbBankEmp_SalaryActionPerformed

    private void btn_save_emp_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_emp_salaryActionPerformed
        updateEmployeeSalaryDetails();
        clearFields();
    }//GEN-LAST:event_btn_save_emp_salaryActionPerformed

    private void txt_emp_sal_al_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_sal_al_1KeyPressed
        Validation.priceText(txt_emp_sal_al_1);
//        txt_emp_sal_al_1.setText(txt_emp_sal_al_1.getText().replaceAll(".0*$", ""));
    }//GEN-LAST:event_txt_emp_sal_al_1KeyPressed

    private void txt_emp_sal_al_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_sal_al_1KeyReleased
        Validation.priceText(txt_emp_sal_al_1);
//        fieldFormat.formatDecimalAmount(txt_emp_sal_al_1);
    }//GEN-LAST:event_txt_emp_sal_al_1KeyReleased

    private void txt_emp_al_2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_al_2KeyPressed
        Validation.priceText(txt_emp_al_2);
//        txt_emp_al_2.setText(txt_emp_al_2.getText().replaceAll(".0*$", ""));
    }//GEN-LAST:event_txt_emp_al_2KeyPressed

    private void txt_emp_al_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_al_2KeyReleased
        Validation.priceText(txt_emp_al_2);
//        fieldFormat.formatDecimalAmount(txt_emp_al_2);
    }//GEN-LAST:event_txt_emp_al_2KeyReleased

    private void txt_emp_al_3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_al_3KeyPressed
        Validation.priceText(txt_emp_al_3);
//        txt_emp_al_3.setText(txt_emp_al_3.getText().replaceAll(".0*$", ""));
    }//GEN-LAST:event_txt_emp_al_3KeyPressed

    private void txt_emp_al_3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_al_3KeyReleased
        Validation.priceText(txt_emp_al_3);
//        fieldFormat.formatDecimalAmount(txt_emp_al_3);
    }//GEN-LAST:event_txt_emp_al_3KeyReleased

    private void txt_emp_al_4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_al_4KeyPressed
        Validation.priceText(txt_emp_al_4);
//        txt_emp_al_4.setText(txt_emp_al_4.getText().replaceAll(".0*$", ""));
    }//GEN-LAST:event_txt_emp_al_4KeyPressed

    private void txt_emp_al_4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_al_4KeyReleased
        Validation.priceText(txt_emp_al_4);
//        fieldFormat.formatDecimalAmount(txt_emp_al_4);
    }//GEN-LAST:event_txt_emp_al_4KeyReleased

    private void cmb_searchEmp_jobTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_searchEmp_jobTypeActionPerformed
        if (cmb_searchEmp_jobType.getSelectedIndex() != 0) {
            try {
                List<M_Employee> allEmployees = employeeController.getAllEmployees();
                if (cmb_searchEmp_jobType.getSelectedItem().toString().equalsIgnoreCase("Sub contractor staff")) {

                    cmb_searchEmp_subContractor.setVisible(true);

                    for (int i = 1; i < cmb_searchEmp_subContractor.getItemCount(); i++) {
                        cmb_searchEmp_subContractor.removeItemAt(i);
                    }

                    for (M_Employee allEmployee : allEmployees) {
                        if (allEmployee.getEmp_jobType_id() == 5) {
                            cmb_searchEmp_subContractor.addItem(allEmployee.getEmp_firstName());
                        }
                    }

                } else {
                    if (cmb_searchEmp_jobType.getSelectedIndex() == 1) {
                        cmb_searchEmp_subContractor.setVisible(false);
                        dtmEmpSalary.setRowCount(0);
                        for (M_Employee allEmployee : allEmployees) {
                            String[] rowData = {allEmployee.getEmp_initials(), allEmployee.getEmp_firstName(), allEmployee.getEmp_middleName(), allEmployee.getEmp_surName()};
                            dtmEmpSalary.addRow(rowData);
                        }
                    } else {

                        cmb_searchEmp_subContractor.setVisible(false);
                        dtmEmpSalary.setRowCount(0);
                        for (M_Employee allEmployee : allEmployees) {
                            if (jobTypeController.searchJobType(cmb_searchEmp_jobType.getSelectedItem().toString()).getJobType_id() == allEmployee.getEmp_jobType_id()) {

                                String[] rowData = {allEmployee.getEmp_initials(), allEmployee.getEmp_firstName(), allEmployee.getEmp_middleName(), allEmployee.getEmp_surName()};
                                dtmEmpSalary.addRow(rowData);

                            }
                        }
                    }
                }

            } catch (Exception ex) {
                Logger.getLogger(Employee_Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmb_searchEmp_jobTypeActionPerformed

    private void cmb_searchEmp_subContractorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_searchEmp_subContractorActionPerformed
        try {
            if (cmb_searchEmp_subContractor.getSelectedIndex() != 0) {
                dtmEmpSalary.setRowCount(0);
                List<M_Employee> allEmployees = employeeController.getAllEmployees();
                for (M_Employee allEmployee : allEmployees) {
                    if (allEmployee.getEmp_subContractor_id() == employeeController.searchEmployee(cmb_searchEmp_subContractor.getSelectedItem().toString()).getEmp_id()) {
                        String[] rowData = {allEmployee.getEmp_initials(), allEmployee.getEmp_firstName(), allEmployee.getEmp_middleName(), allEmployee.getEmp_surName()};
                        dtmEmpSalary.addRow(rowData);
                    }
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(Employee_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmb_searchEmp_subContractorActionPerformed

    private void txt_emp_sal_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_sal_searchActionPerformed
        // TODO add your handling code here:
        txt_emp_sal_search.setText("Search Employee");
        txt_emp_sal_search.setForeground(Color.GRAY);
    }//GEN-LAST:event_txt_emp_sal_searchActionPerformed

    private void txt_emp_sal_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emp_sal_searchMouseClicked
        txt_emp_sal_search.setText("");
        txt_emp_sal_search.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_emp_sal_searchMouseClicked

    private void txt_emp_sal_al_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emp_sal_al_1MouseClicked
        fieldFormat.formatDecimalAmount(txt_emp_sal_basic);
        fieldFormat.clearAmountField(txt_emp_sal_al_1);
    }//GEN-LAST:event_txt_emp_sal_al_1MouseClicked

    private void txt_emp_al_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emp_al_2MouseClicked
        fieldFormat.formatDecimalAmount(txt_emp_sal_al_1);
        fieldFormat.clearAmountField(txt_emp_al_2);
    }//GEN-LAST:event_txt_emp_al_2MouseClicked

    private void txt_emp_al_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emp_al_3MouseClicked
        fieldFormat.formatDecimalAmount(txt_emp_al_2);
        fieldFormat.clearAmountField(txt_emp_al_3);
    }//GEN-LAST:event_txt_emp_al_3MouseClicked

    private void txt_emp_al_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emp_al_4MouseClicked
        fieldFormat.formatDecimalAmount(txt_emp_al_3);
        fieldFormat.clearAmountField(txt_emp_al_4);
    }//GEN-LAST:event_txt_emp_al_4MouseClicked

    private void txt_emp_sal_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_sal_searchKeyReleased
        try {
            dtmEmpSalary.setRowCount(0);
            List<M_Employee> allEmployees = employeeController.getAllEmployeesByLetter(txt_emp_sal_search.getText());
            for (M_Employee allEmployee : allEmployees) {
                String[] rowData = {allEmployee.getEmp_initials(), allEmployee.getEmp_firstName(), allEmployee.getEmp_middleName(), allEmployee.getEmp_surName()};
                dtmEmpSalary.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_emp_sal_searchKeyReleased

    private void txt_emp_sal_al_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_sal_al_1ActionPerformed
        fieldFormat.formatDecimalAmount(txt_emp_sal_al_1);
        txt_emp_al_2.requestFocus();
    }//GEN-LAST:event_txt_emp_sal_al_1ActionPerformed

    private void txt_emp_al_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_al_2ActionPerformed
        fieldFormat.formatDecimalAmount(txt_emp_al_2);
        txt_emp_al_3.requestFocus();
    }//GEN-LAST:event_txt_emp_al_2ActionPerformed

    private void txt_emp_al_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_al_3ActionPerformed
        fieldFormat.formatDecimalAmount(txt_emp_al_3);
        txt_emp_al_4.requestFocus();
    }//GEN-LAST:event_txt_emp_al_3ActionPerformed

    private void txt_emp_al_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_al_4ActionPerformed
        fieldFormat.formatDecimalAmount(txt_emp_al_4);
    }//GEN-LAST:event_txt_emp_al_4ActionPerformed

    private void txt_emp_acc_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_acc_noActionPerformed
        cmbBankEmp_Salary.requestFocus();
    }//GEN-LAST:event_txt_emp_acc_noActionPerformed

    private void cmbBranchEmp_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBranchEmp_salaryActionPerformed
        cmbSalaryType.requestFocus();
    }//GEN-LAST:event_cmbBranchEmp_salaryActionPerformed

    private void cmbSalaryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalaryTypeActionPerformed
        cmbEPFStatus.requestFocus();
    }//GEN-LAST:event_cmbSalaryTypeActionPerformed

    private void cmbEPFStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEPFStatusActionPerformed
        txt_emp_sal_basic.requestFocus();
    }//GEN-LAST:event_cmbEPFStatusActionPerformed

    private void btn_emp_salary_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emp_salary_cancelActionPerformed
        clearFields();
    }//GEN-LAST:event_btn_emp_salary_cancelActionPerformed

    private void txt_emp_sal_basicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_sal_basicKeyTyped

    }//GEN-LAST:event_txt_emp_sal_basicKeyTyped

    private void txt_emp_sal_basicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_sal_basicKeyReleased
        Validation.priceText(txt_emp_sal_basic);
        //        fieldFormat.formatDecimalAmount(txt_emp_sal_basic);
    }//GEN-LAST:event_txt_emp_sal_basicKeyReleased

    private void txt_emp_sal_basicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emp_sal_basicKeyPressed
        Validation.priceText(txt_emp_sal_basic);
        //        txt_emp_sal_basic.setText(txt_emp_sal_basic.getText().replaceAll("\\.?0+$", ""));
    }//GEN-LAST:event_txt_emp_sal_basicKeyPressed

    private void txt_emp_sal_basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_sal_basicActionPerformed
        fieldFormat.formatDecimalAmount(txt_emp_sal_basic);
        txt_emp_sal_al_1.requestFocus();
    }//GEN-LAST:event_txt_emp_sal_basicActionPerformed

    private void txt_emp_sal_basicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emp_sal_basicMouseClicked
        fieldFormat.clearAmountField(txt_emp_sal_basic);
    }//GEN-LAST:event_txt_emp_sal_basicMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Employee_Salary;
    private javax.swing.JPanel bank_panel_hedding4;
    private javax.swing.JButton btn_emp_salary_cancel;
    private javax.swing.JButton btn_save_emp_salary;
    private javax.swing.JComboBox<String> cmbBankEmp_Salary;
    private javax.swing.JComboBox<String> cmbBranchEmp_salary;
    private javax.swing.JComboBox<String> cmbEPFStatus;
    private javax.swing.JComboBox<String> cmbSalaryType;
    private javax.swing.JComboBox<String> cmb_searchEmp_jobType;
    private javax.swing.JComboBox<String> cmb_searchEmp_subContractor;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JTable tb_emp_sal;
    private javax.swing.JPanel tbl_panel_Branch1;
    private javax.swing.JPanel txt_Input_Panel_Branch1;
    private javax.swing.JTextField txt_emp_acc_no;
    private javax.swing.JTextField txt_emp_al_2;
    private javax.swing.JTextField txt_emp_al_3;
    private javax.swing.JTextField txt_emp_al_4;
    private javax.swing.JTextField txt_emp_sal_al_1;
    private javax.swing.JTextField txt_emp_sal_basic;
    private javax.swing.JTextField txt_emp_sal_search;
    private javax.swing.JTextField txt_employee;
    // End of variables declaration//GEN-END:variables

    private void loadEmployeeData() {
        try {

//            if (employee.getEmp_accountNo() == null) {
//                JOptionPane.showMessageDialog(this, "Salary Details not Added to this Employee Yet..");
//            }
            txt_employee.setText(employee.getEmp_firstName() + " " + employee.getEmp_middleName() + " " + employee.getEmp_surName());
            txt_emp_acc_no.setText(employee.getEmp_accountNo());
            if (employee.getEmp_bank_id() != 0) {
                cmbBankEmp_Salary.setSelectedItem(bankController.searchBank(employee.getEmp_bank_id()).getBank_name());
            } else {
                cmbBankEmp_Salary.setSelectedIndex(0);
            }
            if (employee.getEmp_branch_id() != 0) {
                cmbBranchEmp_salary.setSelectedItem(branchController.searchBranch(employee.getEmp_branch_id()).getBranch_name());
            } else {
                cmbBranchEmp_salary.setSelectedIndex(0);
            }
            if (employee.getEmp_salaryType_id() != 0) {
                cmbSalaryType.setSelectedItem(salaryTypeController.searchSalaryType(employee.getEmp_salaryType_id()).getSalaryType_name());
                cmbEPFStatus.setSelectedIndex(Integer.parseInt(employee.getEmp_epf_status()));
            } else {
                cmbSalaryType.setSelectedIndex(0);
                cmbEPFStatus.setSelectedIndex(0);
            }

            txt_emp_sal_basic.setText(decimalFormat.format(employee.getEmp_salary()));
            txt_emp_sal_al_1.setText(decimalFormat.format(employee.getEmp_otherAllowance1()));
            txt_emp_al_2.setText(decimalFormat.format(employee.getEmp_otherAllowance2()));
            txt_emp_al_3.setText(decimalFormat.format(employee.getEmp_otherAllowance3()));
            txt_emp_al_4.setText(decimalFormat.format(employee.getEmp_otherAllowance4()));

        } catch (Exception ex) {
            Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadBankCombo() {
        try {
            cmbBankEmp_Salary.removeAll();
            List<R_Bank> allBanks = bankController.getAllBanks();
            for (R_Bank allBank : allBanks) {
                cmbBankEmp_Salary.addItem(allBank.getBank_name());
            }

        } catch (Exception ex) {
            Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSalTypeCombo() {
        try {
            cmbSalaryType.removeAll();
            List<R_SalaryType> allSalaryTypes = salaryTypeController.getAllSalaryTypes();
            for (R_SalaryType allSalaryType : allSalaryTypes) {
                cmbSalaryType.addItem(allSalaryType.getSalaryType_name());
            }
        } catch (Exception ex) {
            Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadEmpSalTable() {
        try {
            dtmEmpSalary.setRowCount(0);
            List<M_Employee> allEmployees = employeeController.getAllEmployees();
            for (M_Employee allEmployee : allEmployees) {
                String[] rowData = {allEmployee.getEmp_initials(), allEmployee.getEmp_firstName(), allEmployee.getEmp_middleName(), allEmployee.getEmp_surName()};
                dtmEmpSalary.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadBranchCombo() {
        try {
            for (int i = 1; i < cmbBranchEmp_salary.getItemCount(); i++) {
                cmbBranchEmp_salary.removeItemAt(i);
            }

            List<R_Branch> allBranches = branchController.getAllBranches();
            int bankId = bankController.searchBankByName(cmbBankEmp_Salary.getSelectedItem().toString()).getBank_id();
//
            for (R_Branch allBranche : allBranches) {
                if (allBranche.getBranch_bank_id() == bankId) {
                    cmbBranchEmp_salary.addItem(allBranche.getBranch_name());
                } else {
                    cmbBranchEmp_salary.removeAll();
                    cmbBranchEmp_salary.revalidate();
                    cmbBranchEmp_salary.repaint();
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateEmployeeSalaryDetails() {
        if (cmbSalaryType.getSelectedIndex() != 0) {
            try {
                double salary = 0;
                double otherAllowance1 = 0;
                double otherAllowance2 = 0;
                double otherAllowance3 = 0;
                double otherAllowance4 = 0;

                int bankId = 0;
                int branchId = 0;

                int empId = employee.getEmp_id();
                String title = employee.getEmp_title();
                String initials = employee.getEmp_initials();
                String firstName = employee.getEmp_firstName();
                String midName = employee.getEmp_middleName();
                String lastName = employee.getEmp_surName();
                String address1 = employee.getEmp_address1();
                String address2 = employee.getEmp_address2();
                String address3 = employee.getEmp_address3();
                String address4 = employee.getEmp_address4();
                String nic = employee.getEmp_NIC();
                Date dob = employee.getEmp_DOB();
                String contact1 = employee.getEmp_contact1();
                String contact2 = employee.getEmp_contact2();
                String contact3 = employee.getEmp_contatct3();

                String accountNo = txt_emp_acc_no.getText();
                if (cmbBankEmp_Salary.getSelectedIndex() != 0) {
                    bankId = bankController.searchBankByName(cmbBankEmp_Salary.getSelectedItem().toString()).getBank_id();
                }
                if (cmbBranchEmp_salary.getSelectedIndex() != 0) {
                    branchId = branchController.searchBranch(cmbBranchEmp_salary.getSelectedItem().toString(), bankId).getBranch_id();
                }
                int designationId = employee.getEmp_designation_id();

                int salaryTypeId = salaryTypeController.searchSalaryType(cmbSalaryType.getSelectedItem().toString()).getSalaryType_id();
                if (!"".equals(txt_emp_sal_basic.getText())) {
                    salary = Double.parseDouble(txt_emp_sal_basic.getText().replaceAll(",", ""));
                }
                if (!"".equals(txt_emp_sal_al_1.getText())) {
                    otherAllowance1 = Double.parseDouble(txt_emp_sal_al_1.getText().replaceAll(",", ""));
                }
                if (!"".equals(txt_emp_al_2.getText())) {
                    otherAllowance2 = Double.parseDouble(txt_emp_al_2.getText().replaceAll(",", ""));
                }

                int siteId = employee.getEmp_site_id();
                String status = employee.getEmp_status();

                String epfStatus = Integer.toString(cmbEPFStatus.getSelectedIndex());

                int jobTypeId = employee.getEmp_jobType_id();
                Date joinDate = employee.getEmp_joinDate();
                int subContractorId = employee.getEmp_subContractor_id();
                if (!"".equals(txt_emp_al_3.getText())) {
                    otherAllowance3 = Double.parseDouble(txt_emp_al_3.getText().replaceAll(",", ""));
                }
                if (!"".equals(txt_emp_al_4.getText())) {
                    otherAllowance4 = Double.parseDouble(txt_emp_al_4.getText().replaceAll(",", ""));
                }

                M_Employee employeeUpdate = new M_Employee(empId, title, initials, firstName, midName, lastName, address1, address2, address3, address4, nic, dob, contact1, contact2, contact3, accountNo, bankId, branchId, designationId, salaryTypeId, salary, otherAllowance1, otherAllowance2, siteId, status, epfStatus, jobTypeId, joinDate, subContractorId, otherAllowance3, otherAllowance4);
                boolean updateEmployee = employeeController.updateEmployee(employeeUpdate);
                if (updateEmployee) {
                    JOptionPane.showMessageDialog(this, "Employee Salary Details Updated Successfully..");
                } else {
                    JOptionPane.showMessageDialog(this, "Updating Employee Salary Details Occured a Error..");
                }
                loadEmpSalTable();

            } catch (Exception ex) {
                Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Check that the Salary Type is Selected");
        }
    }

    private void loadJobTypeCombo() {
        try {
            cmb_searchEmp_jobType.removeAll();
            List<R_JobType> allJobTypes = jobTypeController.getAllJobTypes();
            for (R_JobType allJobType : allJobTypes) {
                cmb_searchEmp_jobType.addItem(allJobType.getJobType_name());
            }
        } catch (Exception ex) {
            Logger.getLogger(Employee_Salary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearFields() {
        txt_employee.setText("");
        txt_emp_acc_no.setText("");
        cmbBankEmp_Salary.setSelectedIndex(0);
        cmbBranchEmp_salary.setSelectedIndex(0);
        cmbSalaryType.setSelectedIndex(0);
        cmbEPFStatus.setSelectedIndex(0);
        txt_emp_sal_basic.setText("");
        txt_emp_sal_al_1.setText("");
        txt_emp_al_2.setText("");
        txt_emp_al_3.setText("");
        txt_emp_al_4.setText("");
        txt_emp_acc_no.requestFocus();
    }

}
