/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brotherssoft.samodconstructions.view;

import com.brotherssoft.samodconstructions.controller.M_PurchaserController;
import com.brotherssoft.samodconstructions.controller.R_BankController;
import com.brotherssoft.samodconstructions.controller.R_BranchController;
import com.brotherssoft.samodconstructions.custom.IDGenerator;
import com.brotherssoft.samodconstructions.model.M_Purchaser;
import com.brotherssoft.samodconstructions.model.R_Bank;
import com.brotherssoft.samodconstructions.model.R_Branch;
import com.brotherssoft.samodconstructions.serverconnector.ServerConnector;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akvasoft
 */
public class Purchaser_Registration_Panel extends javax.swing.JPanel {

    R_BankController bankController;
    R_BranchController branchController;
    M_PurchaserController purchaserController;

    DefaultTableModel dtmPurchaser;

    /**
     * Creates new form Purchaser_Registration_Panel
     */
    public Purchaser_Registration_Panel() throws Exception {
        initComponents();

        bankController = ServerConnector.getServerConnetor().getBankController();
        branchController = ServerConnector.getServerConnetor().getBranchController();
        purchaserController = ServerConnector.getServerConnetor().getPurchaserController();
        dtmPurchaser = (DefaultTableModel) tbl_purchaser_info.getModel();

        loadBankCombo();
        loadPurchaserTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Purchaser_Registration_Panel = new javax.swing.JPanel();
        user_panel_hedding11 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        bank_panel_input_area6 = new javax.swing.JPanel();
        jLabel166 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        txt_purchaser_name = new javax.swing.JTextField();
        txt_purchaser_address = new javax.swing.JTextField();
        btn_save_purchaser = new javax.swing.JButton();
        btn_purchaser_new = new javax.swing.JButton();
        cmb_purchaser_bank = new javax.swing.JComboBox<>();
        btn_purchaser = new javax.swing.JButton();
        jLabel176 = new javax.swing.JLabel();
        txt_purchaser_accountNo = new javax.swing.JTextField();
        jLabel177 = new javax.swing.JLabel();
        cmb_purchaser_branch = new javax.swing.JComboBox<>();
        jLabel178 = new javax.swing.JLabel();
        txt_purchaser_contact1 = new javax.swing.JTextField();
        jLabel179 = new javax.swing.JLabel();
        txt_purchaser_contact2 = new javax.swing.JTextField();
        jLabel180 = new javax.swing.JLabel();
        txt_purchaser_repName = new javax.swing.JTextField();
        jLabel181 = new javax.swing.JLabel();
        txt_purchaser_repContact = new javax.swing.JTextField();
        jLabel182 = new javax.swing.JLabel();
        cmb_purchaser_status = new javax.swing.JComboBox<>();
        bank_panel_tbl10 = new javax.swing.JPanel();
        jScrollPane25 = new javax.swing.JScrollPane();
        tbl_purchaser_info = new javax.swing.JTable();
        txt_search_purchaser = new javax.swing.JTextField();

        Purchaser_Registration_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Purchaser_Registration_Panel.setPreferredSize(new java.awt.Dimension(1050, 710));

        user_panel_hedding11.setBackground(new java.awt.Color(122, 72, 222));

        jLabel92.setBackground(new java.awt.Color(255, 255, 255));
        jLabel92.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(204, 204, 255));
        jLabel92.setText("Administrations / System Management / Master Details /");

        jLabel93.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(204, 204, 204));
        jLabel93.setText("Purchaser Registration");

        javax.swing.GroupLayout user_panel_hedding11Layout = new javax.swing.GroupLayout(user_panel_hedding11);
        user_panel_hedding11.setLayout(user_panel_hedding11Layout);
        user_panel_hedding11Layout.setHorizontalGroup(
            user_panel_hedding11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_panel_hedding11Layout.createSequentialGroup()
                .addGroup(user_panel_hedding11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(user_panel_hedding11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(user_panel_hedding11Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel93)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator23)))
                .addContainerGap())
        );
        user_panel_hedding11Layout.setVerticalGroup(
            user_panel_hedding11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_panel_hedding11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user_panel_hedding11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel93)
                    .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        bank_panel_input_area6.setBackground(new java.awt.Color(255, 255, 255));
        bank_panel_input_area6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save And Modify Purchaser", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel166.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel166.setText("Purchaser Name");

        jLabel173.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel173.setText("Purchaser Address");

        jLabel174.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel174.setText("Bank");

        txt_purchaser_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txt_purchaser_address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btn_save_purchaser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_save_purchaser.setText("Save");
        btn_save_purchaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_purchaserActionPerformed(evt);
            }
        });

        btn_purchaser_new.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_purchaser_new.setText("New");
        btn_purchaser_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_purchaser_newActionPerformed(evt);
            }
        });

        cmb_purchaser_bank.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_purchaser_bank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Bank -" }));
        cmb_purchaser_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_purchaser_bankActionPerformed(evt);
            }
        });

        btn_purchaser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_purchaser.setText("Branch");
        btn_purchaser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_purchaserMouseClicked(evt);
            }
        });

        jLabel176.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel176.setText("Account No");

        txt_purchaser_accountNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel177.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel177.setText("Branch");

        cmb_purchaser_branch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_purchaser_branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Branch -" }));

        jLabel178.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel178.setText("Contact 1");

        txt_purchaser_contact1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel179.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel179.setText("Contact 2");

        txt_purchaser_contact2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel180.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel180.setText("Rep Name");

        txt_purchaser_repName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel181.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel181.setText("Rep Contact");

        txt_purchaser_repContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel182.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel182.setText("Status");

        cmb_purchaser_status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_purchaser_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        javax.swing.GroupLayout bank_panel_input_area6Layout = new javax.swing.GroupLayout(bank_panel_input_area6);
        bank_panel_input_area6.setLayout(bank_panel_input_area6Layout);
        bank_panel_input_area6Layout.setHorizontalGroup(
            bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel166, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_purchaser_name))
                    .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel173, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_purchaser_address))
                    .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel174, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_purchaser_bank, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_input_area6Layout.createSequentialGroup()
                        .addGap(0, 188, Short.MAX_VALUE)
                        .addComponent(btn_purchaser, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save_purchaser, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_purchaser_new, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel176, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_purchaser_accountNo))
                    .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel177, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_purchaser_branch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel178, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_purchaser_contact1))
                    .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel179, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_purchaser_contact2))
                    .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel180, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_purchaser_repName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel181, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_purchaser_repContact))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_input_area6Layout.createSequentialGroup()
                        .addComponent(jLabel182, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_purchaser_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bank_panel_input_area6Layout.setVerticalGroup(
            bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_input_area6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel166, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchaser_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel173, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchaser_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel176, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchaser_accountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel174, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_purchaser_bank))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel177, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_purchaser_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel178, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchaser_contact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel179, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchaser_contact2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel180, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchaser_repName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel181, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchaser_repContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel182, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_purchaser_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(bank_panel_input_area6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_purchaser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_purchaser_new, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_purchaser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bank_panel_tbl10.setBackground(new java.awt.Color(255, 255, 255));
        bank_panel_tbl10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchaser Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        tbl_purchaser_info.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbl_purchaser_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Purchaser Name"
            }
        ));
        tbl_purchaser_info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_purchaser_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_purchaser_infoMouseClicked(evt);
            }
        });
        jScrollPane25.setViewportView(tbl_purchaser_info);

        txt_search_purchaser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_search_purchaser.setForeground(new java.awt.Color(102, 102, 102));
        txt_search_purchaser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_search_purchaser.setText("Search Purchaser");
        txt_search_purchaser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search_purchaserMouseClicked(evt);
            }
        });
        txt_search_purchaser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_purchaserKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout bank_panel_tbl10Layout = new javax.swing.GroupLayout(bank_panel_tbl10);
        bank_panel_tbl10.setLayout(bank_panel_tbl10Layout);
        bank_panel_tbl10Layout.setHorizontalGroup(
            bank_panel_tbl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_tbl10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search_purchaser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bank_panel_tbl10Layout.setVerticalGroup(
            bank_panel_tbl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_tbl10Layout.createSequentialGroup()
                .addComponent(txt_search_purchaser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Purchaser_Registration_PanelLayout = new javax.swing.GroupLayout(Purchaser_Registration_Panel);
        Purchaser_Registration_Panel.setLayout(Purchaser_Registration_PanelLayout);
        Purchaser_Registration_PanelLayout.setHorizontalGroup(
            Purchaser_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Purchaser_Registration_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bank_panel_input_area6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bank_panel_tbl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(user_panel_hedding11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Purchaser_Registration_PanelLayout.setVerticalGroup(
            Purchaser_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Purchaser_Registration_PanelLayout.createSequentialGroup()
                .addComponent(user_panel_hedding11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Purchaser_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bank_panel_input_area6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bank_panel_tbl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Purchaser_Registration_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Purchaser_Registration_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_purchaserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_purchaserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_purchaserMouseClicked

    private void cmb_purchaser_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_purchaser_bankActionPerformed
        if (cmb_purchaser_bank.getSelectedIndex() != 0) {
            loadBranchCombo();
        }
    }//GEN-LAST:event_cmb_purchaser_bankActionPerformed

    private void btn_save_purchaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_purchaserActionPerformed
        if (btn_save_purchaser.getText().equalsIgnoreCase("Save")) {
            savePurchaser();
        } else {
            updatePurchaser();
        }
    }//GEN-LAST:event_btn_save_purchaserActionPerformed

    private void tbl_purchaser_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_purchaser_infoMouseClicked
        getFromPurchaserTable();
        txt_search_purchaser.setText("Search Purchaser");
        txt_search_purchaser.setForeground(Color.GRAY);
    }//GEN-LAST:event_tbl_purchaser_infoMouseClicked

    private void btn_purchaser_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_purchaser_newActionPerformed
        txt_purchaser_name.setText("");
        txt_purchaser_address.setText("");
        txt_purchaser_accountNo.setText("");
        cmb_purchaser_bank.setSelectedIndex(0);
        cmb_purchaser_branch.setSelectedIndex(0);
        txt_purchaser_contact1.setText("");
        txt_purchaser_contact2.setText("");
        txt_purchaser_repName.setText("");
        txt_purchaser_repContact.setText("");
        cmb_purchaser_status.setSelectedIndex(0);

        btn_save_purchaser.setText("Save");
    }//GEN-LAST:event_btn_purchaser_newActionPerformed

    private void txt_search_purchaserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_purchaserKeyReleased
        try {

            dtmPurchaser.setRowCount(0);
            List<M_Purchaser> allPurchasers = purchaserController.getAllPurchasersByLetter(txt_search_purchaser.getText());
            for (M_Purchaser allPurchaser : allPurchasers) {
                String[] rowData = {allPurchaser.getPurchaser_name()};
                dtmPurchaser.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(Purchaser_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_search_purchaserKeyReleased

    private void txt_search_purchaserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search_purchaserMouseClicked
        txt_search_purchaser.setText("");
        txt_search_purchaser.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_search_purchaserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Purchaser_Registration_Panel;
    private javax.swing.JPanel bank_panel_input_area6;
    private javax.swing.JPanel bank_panel_tbl10;
    private javax.swing.JButton btn_purchaser;
    private javax.swing.JButton btn_purchaser_new;
    private javax.swing.JButton btn_save_purchaser;
    private javax.swing.JComboBox<String> cmb_purchaser_bank;
    private javax.swing.JComboBox<String> cmb_purchaser_branch;
    private javax.swing.JComboBox<String> cmb_purchaser_status;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JTable tbl_purchaser_info;
    private javax.swing.JTextField txt_purchaser_accountNo;
    private javax.swing.JTextField txt_purchaser_address;
    private javax.swing.JTextField txt_purchaser_contact1;
    private javax.swing.JTextField txt_purchaser_contact2;
    private javax.swing.JTextField txt_purchaser_name;
    private javax.swing.JTextField txt_purchaser_repContact;
    private javax.swing.JTextField txt_purchaser_repName;
    private javax.swing.JTextField txt_search_purchaser;
    private javax.swing.JPanel user_panel_hedding11;
    // End of variables declaration//GEN-END:variables

    private void loadBankCombo() {
        try {

            List<R_Bank> allBanks = bankController.getAllBanks();
            cmb_purchaser_bank.removeAll();
            for (R_Bank allBank : allBanks) {
                cmb_purchaser_bank.addItem(allBank.getBank_name());
            }

        } catch (Exception ex) {
            Logger.getLogger(Purchaser_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadPurchaserTable() {
        try {

            dtmPurchaser.setRowCount(0);
            List<M_Purchaser> allPurchasers = purchaserController.getAllPurchasers();
            for (M_Purchaser allPurchaser : allPurchasers) {
                String[] rowData = {allPurchaser.getPurchaser_name()};
                dtmPurchaser.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(Purchaser_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadBranchCombo() {
        try {

            for (int i = 1; i < cmb_purchaser_branch.getItemCount(); i++) {
                cmb_purchaser_branch.removeItemAt(i);
            }

            List<R_Branch> allBranches = branchController.getAllBranches();
            int bankId = bankController.searchBankByName(cmb_purchaser_bank.getSelectedItem().toString()).getBank_id();
//
            for (R_Branch allBranche : allBranches) {
                if (allBranche.getBranch_bank_id() == bankId) {
                    cmb_purchaser_branch.addItem(allBranche.getBranch_name());
                } else {
                    cmb_purchaser_branch.removeAll();
                    cmb_purchaser_branch.revalidate();
                    cmb_purchaser_branch.repaint();
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(Purchaser_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void savePurchaser() {
        try {

            int purchaserId = IDGenerator.getNewID("m_purchaser", "PURCHASER_ID");
            String purchaserName = txt_purchaser_name.getText();
            String purchaserAddress = txt_purchaser_address.getText();
            String purchaserAccountNo = txt_purchaser_accountNo.getText();
            int bankId = bankController.searchBankByName(cmb_purchaser_bank.getSelectedItem().toString()).getBank_id();
            int branchId = branchController.searchBranch(cmb_purchaser_branch.getSelectedItem().toString(), bankId).getBranch_id();
            String contact1 = txt_purchaser_contact1.getText();
            String contact2 = txt_purchaser_contact2.getText();
            String repName = txt_purchaser_repName.getText();
            String repContact = txt_purchaser_repContact.getText();
            String status = null;
            if (cmb_purchaser_status.getSelectedIndex() == 0) {
                status = "A";
            } else {
                status = "I";
            }

            M_Purchaser purchaser = new M_Purchaser(purchaserId, purchaserName, purchaserAddress, purchaserAccountNo, bankId, branchId, contact1, contact2, repName, repContact, status);
            boolean addPurchaser = purchaserController.addPurchaser(purchaser);
            if (addPurchaser) {
                JOptionPane.showMessageDialog(this, "Purchaser Details Saved Successfully..");
            } else {
                JOptionPane.showMessageDialog(this, "Purchaser Details Saving Cannot Proceed..");
            }

        } catch (Exception ex) {
            Logger.getLogger(Purchaser_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

        loadPurchaserTable();
    }

    private void getFromPurchaserTable() {
        try {

            M_Purchaser purchaser = searchFromTablePurchaserName();

            txt_purchaser_name.setText(purchaser.getPurchaser_name());
            txt_purchaser_address.setText(purchaser.getPurchaser_address());
            txt_purchaser_accountNo.setText(purchaser.getPurchaser_accountNo());
            cmb_purchaser_bank.setSelectedItem(bankController.searchBank(purchaser.getPurchaser_bank_id()).getBank_name());
            cmb_purchaser_branch.setSelectedItem(branchController.searchBranch(purchaser.getPurchaser_branch_id()).getBranch_name());
            txt_purchaser_contact1.setText(purchaser.getPurchaser_contact1());
            txt_purchaser_contact2.setText(purchaser.getPurchaser_contact2());
            txt_purchaser_repName.setText(purchaser.getPurchaser_repName());
            txt_purchaser_repContact.setText(purchaser.getPurchaser_repContact());
            if (purchaser.getPurchaser_status().equalsIgnoreCase("A")) {
                cmb_purchaser_status.setSelectedIndex(0);
            } else {
                cmb_purchaser_status.setSelectedIndex(1);
            }

        } catch (Exception ex) {
            Logger.getLogger(Purchaser_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

        btn_save_purchaser.setText("Update");
    }

    private M_Purchaser searchFromTablePurchaserName() {
        M_Purchaser searchPurchaser = null;
        try {

            int selectedRow = tbl_purchaser_info.getSelectedRow();
            String purchaserName = (String) dtmPurchaser.getValueAt(selectedRow, 0);
            searchPurchaser = purchaserController.searchPurchaser(purchaserName);

        } catch (Exception ex) {
            Logger.getLogger(Purchaser_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return searchPurchaser;
    }

    private void updatePurchaser() {
        try {

            int purchaserId = searchFromTablePurchaserName().getPurchaser_id();
            String purchaserName = txt_purchaser_name.getText();
            String purchaserAddress = txt_purchaser_address.getText();
            String purchaserAccountNo = txt_purchaser_accountNo.getText();
            int bankId = bankController.searchBankByName(cmb_purchaser_bank.getSelectedItem().toString()).getBank_id();
            int branchId = branchController.searchBranch(cmb_purchaser_branch.getSelectedItem().toString(), bankId).getBranch_id();
            String contact1 = txt_purchaser_contact1.getText();
            String contact2 = txt_purchaser_contact2.getText();
            String repName = txt_purchaser_repName.getText();
            String repContact = txt_purchaser_repContact.getText();
            String status = null;
            if (cmb_purchaser_status.getSelectedIndex() == 0) {
                status = "A";
            } else {
                status = "I";
            }

            M_Purchaser purchaser = new M_Purchaser(purchaserId, purchaserName, purchaserAddress, purchaserAccountNo, bankId, branchId, contact1, contact2, repName, repContact, status);
            boolean updatePuchaser = purchaserController.updatePuchaser(purchaser);
            if (updatePuchaser) {
                JOptionPane.showMessageDialog(this, "Purchaser Details Updated Successfully..");
            } else {
                JOptionPane.showMessageDialog(this, "Updating Purchaser Details Failed..");
            }

        } catch (Exception ex) {
            Logger.getLogger(Purchaser_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }

        loadPurchaserTable();
    }
}
