/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brotherssoft.samodconstructions.view;

import com.brotherssoft.samodconstructions.controller.M_VehicleController;
import com.brotherssoft.samodconstructions.controller.R_FuelTypeController;
import com.brotherssoft.samodconstructions.controller.R_VehivleTypeController;
import com.brotherssoft.samodconstructions.controller.T_RunchartController;
import com.brotherssoft.samodconstructions.custom.AmountFieldFormat;
import com.brotherssoft.samodconstructions.custom.IDGenerator;
import com.brotherssoft.samodconstructions.custom.Validation;
import com.brotherssoft.samodconstructions.model.M_Vehicle;
import com.brotherssoft.samodconstructions.model.T_Runchart;
import com.brotherssoft.samodconstructions.serverconnector.ServerConnector;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akvasoft
 */
public class Running_Chart extends javax.swing.JPanel {

    M_VehicleController vehicleController;
    T_RunchartController runchartController;
    R_VehivleTypeController vehivleTypeController;
    R_FuelTypeController fuelTypeController;
    DefaultTableModel dtmRunchart;

    AmountFieldFormat fieldFormat = new AmountFieldFormat();
    DecimalFormat decimalFormat = new DecimalFormat("#,##0.00");
    JSpinner.DateEditor de1;
    JSpinner.DateEditor de2;
    Date date = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);

    T_Runchart runchartGlobal = null;
    public static int runChartIdPub;

    /**
     * Creates new form Running_Chart
     */
    public Running_Chart() throws Exception {
        initComponents();
        DisablePanels();
        Chart_View_Panel.setVisible(true);
        date_picker_joinDate.setFormats("yyyy-MM-dd","yyyy/MM/dd");
        de1 = new JSpinner.DateEditor(spn_start_time, "HH:mm a");
        de2 = new JSpinner.DateEditor(spn_end_time, "HH:mm a");

        vehicleController = ServerConnector.getServerConnetor().getVehicleController();
        runchartController = ServerConnector.getServerConnetor().getRunchartController();
        vehivleTypeController = ServerConnector.getServerConnetor().getVehivleTypeController();
        fuelTypeController = ServerConnector.getServerConnetor().getFuelTypeController();
        dtmRunchart = (DefaultTableModel) tbl_runchart.getModel();

        loadVehicleCombo();
        loadRunchartTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Chart_Registration_Panel = new javax.swing.JPanel();
        bank_panel_hedding3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txt_Input_Panel_Branch2 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_type_of_vehi = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_fuel_type = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_start = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txt_end = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txt_distance = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txt_fuel_odometer = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txt_fuel_quantity = new javax.swing.JTextField();
        date_picker_joinDate = new org.jdesktop.swingx.JXDatePicker();
        btn_emp_new = new javax.swing.JButton();
        btn_save_runchart = new javax.swing.JButton();
        btn_emp_salary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        spn_start_time = new javax.swing.JSpinner(sm);
        Date date2 = new Date();
        SpinnerDateModel sm2 = new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        spn_end_time = new javax.swing.JSpinner(sm2);
        jLabel58 = new javax.swing.JLabel();
        txt_fuel_price = new javax.swing.JTextField();
        cmb_status = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_vehicle = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Chart_View_Panel = new javax.swing.JPanel();
        bank_panel_hedding5 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        tbl_panel_Branch2 = new javax.swing.JPanel();
        btn_branch1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_runchart = new javax.swing.JTable();
        txt_search_run = new javax.swing.JTextField();

        Chart_Registration_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Chart_Registration_Panel.setPreferredSize(new java.awt.Dimension(1050, 710));

        bank_panel_hedding3.setBackground(new java.awt.Color(122, 72, 222));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 255));
        jLabel24.setText("Administrations / System Management / Operations /");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("New Running Chart");

        javax.swing.GroupLayout bank_panel_hedding3Layout = new javax.swing.GroupLayout(bank_panel_hedding3);
        bank_panel_hedding3.setLayout(bank_panel_hedding3Layout);
        bank_panel_hedding3Layout.setHorizontalGroup(
            bank_panel_hedding3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_hedding3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(509, Short.MAX_VALUE))
            .addGroup(bank_panel_hedding3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9))
        );
        bank_panel_hedding3Layout.setVerticalGroup(
            bank_panel_hedding3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_hedding3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bank_panel_hedding3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        txt_Input_Panel_Branch2.setBackground(new java.awt.Color(255, 255, 255));
        txt_Input_Panel_Branch2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Necessary Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel31.setText("Select Vehical");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel29.setText("Type of Vehical");

        txt_type_of_vehi.setEditable(false);
        txt_type_of_vehi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_type_of_vehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_type_of_vehiActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel30.setText("Fuel Type");

        txt_fuel_type.setEditable(false);
        txt_fuel_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_fuel_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fuel_typeActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel33.setText("Date");

        jLabel47.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel47.setText("Description");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel34.setText("Start");

        txt_start.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_startMouseClicked(evt);
            }
        });
        txt_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_startActionPerformed(evt);
            }
        });
        txt_start.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_startKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_startKeyReleased(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel49.setText("End");

        txt_end.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_end.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_endMouseClicked(evt);
            }
        });
        txt_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endActionPerformed(evt);
            }
        });
        txt_end.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_endKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_endKeyReleased(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel50.setText("Distance");

        txt_distance.setEditable(false);
        txt_distance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_distance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_distanceMouseClicked(evt);
            }
        });
        txt_distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_distanceActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel51.setText("Start");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel52.setText("End");

        jLabel54.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel54.setText("Odometer");

        txt_fuel_odometer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_fuel_odometer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_fuel_odometerMouseClicked(evt);
            }
        });
        txt_fuel_odometer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fuel_odometerActionPerformed(evt);
            }
        });
        txt_fuel_odometer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fuel_odometerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fuel_odometerKeyReleased(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel55.setText("Quantity");

        txt_fuel_quantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_fuel_quantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_fuel_quantityMouseClicked(evt);
            }
        });
        txt_fuel_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fuel_quantityActionPerformed(evt);
            }
        });
        txt_fuel_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fuel_quantityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fuel_quantityKeyReleased(evt);
            }
        });

        date_picker_joinDate.setDate(new Date());
        date_picker_joinDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_picker_joinDateActionPerformed(evt);
            }
        });

        btn_emp_new.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_emp_new.setText("New");
        btn_emp_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emp_newActionPerformed(evt);
            }
        });

        btn_save_runchart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_save_runchart.setText("Save");
        btn_save_runchart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_runchartActionPerformed(evt);
            }
        });

        btn_emp_salary.setBackground(new java.awt.Color(255, 0, 51));
        btn_emp_salary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_emp_salary.setText("Delete");
        btn_emp_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emp_salaryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Odometer");

        txt_desc.setColumns(20);
        txt_desc.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txt_desc.setRows(5);
        jScrollPane1.setViewportView(txt_desc);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Time");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Vehical");

        JSpinner.DateEditor de = new JSpinner.DateEditor(spn_start_time,"HH:mm a");
        spn_start_time.setEditor(de);
        spn_start_time.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn_start_timeStateChanged(evt);
            }
        });
        spn_start_time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spn_start_timeMouseClicked(evt);
            }
        });
        spn_start_time.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spn_start_timePropertyChange(evt);
            }
        });
        spn_start_time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spn_start_timeKeyPressed(evt);
            }
        });

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(spn_end_time,"HH:mm a");
        spn_end_time.setEditor(de2);

        jLabel58.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel58.setText("Price");

        txt_fuel_price.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_fuel_price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_fuel_priceMouseClicked(evt);
            }
        });
        txt_fuel_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fuel_priceActionPerformed(evt);
            }
        });
        txt_fuel_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fuel_priceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fuel_priceKeyReleased(evt);
            }
        });

        cmb_status.setEditable(true);
        cmb_status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE" }));
        cmb_status.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_statusMouseClicked(evt);
            }
        });
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel32.setText("Status");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Fuel Received");

        cmb_vehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Vehicle -" }));
        cmb_vehicle.setPreferredSize(new java.awt.Dimension(56, 26));
        cmb_vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_vehicleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("km");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("km");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("km");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel56.setText("Liters");

        jLabel62.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel62.setText("Rupees");

        javax.swing.GroupLayout txt_Input_Panel_Branch2Layout = new javax.swing.GroupLayout(txt_Input_Panel_Branch2);
        txt_Input_Panel_Branch2.setLayout(txt_Input_Panel_Branch2Layout);
        txt_Input_Panel_Branch2Layout.setHorizontalGroup(
            txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_type_of_vehi)
                                    .addComponent(cmb_vehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(date_picker_joinDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_end, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_start, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_distance, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)))))
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txt_fuel_type))))
                    .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(317, 317, 317)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spn_end_time, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spn_start_time, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_fuel_odometer, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_Input_Panel_Branch2Layout.createSequentialGroup()
                            .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmb_status, javax.swing.GroupLayout.Alignment.TRAILING, 0, 356, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                    .addComponent(txt_fuel_quantity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel56))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                    .addComponent(txt_fuel_price)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel62))))))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txt_Input_Panel_Branch2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_save_runchart, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btn_emp_new, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btn_emp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        txt_Input_Panel_Branch2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_emp_new, btn_emp_salary, btn_save_runchart});

        txt_Input_Panel_Branch2Layout.setVerticalGroup(
            txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_type_of_vehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_fuel_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_picker_joinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txt_Input_Panel_Branch2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spn_start_time, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spn_end_time, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fuel_odometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fuel_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fuel_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(9, 9, 9)))
                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(txt_Input_Panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_save_runchart)
                    .addComponent(btn_emp_new)
                    .addComponent(btn_emp_salary))
                .addGap(36, 36, 36))
        );

        txt_Input_Panel_Branch2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_emp_new, btn_emp_salary, btn_save_runchart});

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("List of Charts");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Chart_Registration_PanelLayout = new javax.swing.GroupLayout(Chart_Registration_Panel);
        Chart_Registration_Panel.setLayout(Chart_Registration_PanelLayout);
        Chart_Registration_PanelLayout.setHorizontalGroup(
            Chart_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bank_panel_hedding3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Chart_Registration_PanelLayout.createSequentialGroup()
                .addGroup(Chart_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Chart_Registration_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_Input_Panel_Branch2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Chart_Registration_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Chart_Registration_PanelLayout.setVerticalGroup(
            Chart_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Chart_Registration_PanelLayout.createSequentialGroup()
                .addComponent(bank_panel_hedding3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Input_Panel_Branch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Chart_View_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Chart_View_Panel.setPreferredSize(new java.awt.Dimension(1050, 710));

        bank_panel_hedding5.setBackground(new java.awt.Color(122, 72, 222));

        jLabel60.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(204, 204, 255));
        jLabel60.setText("Administrations / System Management / Operations/Running Chart");

        jLabel61.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(204, 204, 204));
        jLabel61.setText("Show Charts");

        javax.swing.GroupLayout bank_panel_hedding5Layout = new javax.swing.GroupLayout(bank_panel_hedding5);
        bank_panel_hedding5.setLayout(bank_panel_hedding5Layout);
        bank_panel_hedding5Layout.setHorizontalGroup(
            bank_panel_hedding5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_hedding5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bank_panel_hedding5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11))
        );
        bank_panel_hedding5Layout.setVerticalGroup(
            bank_panel_hedding5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_hedding5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bank_panel_hedding5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel61)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tbl_panel_Branch2.setBackground(new java.awt.Color(255, 255, 255));
        tbl_panel_Branch2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Running Chart Infomations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        btn_branch1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_branch1.setText("New Chart");
        btn_branch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_branch1MouseClicked(evt);
            }
        });
        btn_branch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_branch1ActionPerformed(evt);
            }
        });

        tbl_runchart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbl_runchart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vehical", "Date", "Description", "Start", "End", "Fuel(Ltr)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_runchart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_runchart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_runchartMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tbl_runchart);

        txt_search_run.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_search_run.setForeground(new java.awt.Color(102, 102, 102));
        txt_search_run.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_search_run.setText("Search By Vehical Number");
        txt_search_run.setToolTipText("Use Bank Nname To Search !");
        txt_search_run.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search_runMouseClicked(evt);
            }
        });
        txt_search_run.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_search_runKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_runKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_search_runKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout tbl_panel_Branch2Layout = new javax.swing.GroupLayout(tbl_panel_Branch2);
        tbl_panel_Branch2.setLayout(tbl_panel_Branch2Layout);
        tbl_panel_Branch2Layout.setHorizontalGroup(
            tbl_panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
            .addGroup(tbl_panel_Branch2Layout.createSequentialGroup()
                .addComponent(btn_branch1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search_run, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tbl_panel_Branch2Layout.setVerticalGroup(
            tbl_panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbl_panel_Branch2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbl_panel_Branch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_branch1)
                    .addComponent(txt_search_run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Chart_View_PanelLayout = new javax.swing.GroupLayout(Chart_View_Panel);
        Chart_View_Panel.setLayout(Chart_View_PanelLayout);
        Chart_View_PanelLayout.setHorizontalGroup(
            Chart_View_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bank_panel_hedding5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Chart_View_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_panel_Branch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        Chart_View_PanelLayout.setVerticalGroup(
            Chart_View_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Chart_View_PanelLayout.createSequentialGroup()
                .addComponent(bank_panel_hedding5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbl_panel_Branch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(Chart_Registration_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Chart_View_Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Chart_View_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Chart_Registration_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Chart_View_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Chart_Registration_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_type_of_vehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_type_of_vehiActionPerformed

    }//GEN-LAST:event_txt_type_of_vehiActionPerformed

    private void txt_fuel_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fuel_typeActionPerformed

    }//GEN-LAST:event_txt_fuel_typeActionPerformed

    private void txt_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_startActionPerformed
        fieldFormat.formatDecimalAmount(txt_start);
        fieldFormat.clearAmountField(txt_end);
        txt_end.requestFocus();
    }//GEN-LAST:event_txt_startActionPerformed

    private void txt_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endActionPerformed
        calculateDistance();
        fieldFormat.formatDecimalAmount(txt_end);
        spn_start_time.requestFocus();
    }//GEN-LAST:event_txt_endActionPerformed

    private void txt_distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_distanceActionPerformed

    }//GEN-LAST:event_txt_distanceActionPerformed

    private void txt_fuel_odometerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fuel_odometerActionPerformed
        fieldFormat.formatDecimalAmount(txt_fuel_odometer);
        fieldFormat.clearAmountField(txt_fuel_quantity);
        txt_fuel_quantity.requestFocus();
    }//GEN-LAST:event_txt_fuel_odometerActionPerformed

    private void txt_fuel_odometerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fuel_odometerKeyPressed
        Validation.priceText(txt_fuel_odometer);
    }//GEN-LAST:event_txt_fuel_odometerKeyPressed

    private void txt_fuel_odometerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fuel_odometerKeyReleased
        Validation.priceText(txt_fuel_odometer);
    }//GEN-LAST:event_txt_fuel_odometerKeyReleased

    private void txt_fuel_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fuel_quantityActionPerformed
        fieldFormat.formatDecimalAmount(txt_fuel_quantity);
        fieldFormat.clearAmountField(txt_fuel_price);
        txt_fuel_price.requestFocus();
    }//GEN-LAST:event_txt_fuel_quantityActionPerformed

    private void txt_fuel_quantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fuel_quantityKeyPressed
        Validation.priceText(txt_fuel_quantity);
    }//GEN-LAST:event_txt_fuel_quantityKeyPressed

    private void txt_fuel_quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fuel_quantityKeyReleased
        Validation.priceText(txt_fuel_quantity);
    }//GEN-LAST:event_txt_fuel_quantityKeyReleased

    private void date_picker_joinDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_picker_joinDateActionPerformed
        txt_desc.requestFocus();
    }//GEN-LAST:event_date_picker_joinDateActionPerformed

    private void btn_emp_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emp_newActionPerformed
        clearFields();
        try {
            runchartController.releaseRunchart(runchartGlobal.getRunchart_id());
        } catch (Exception ex) {
            Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_emp_newActionPerformed

    private void btn_save_runchartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_runchartActionPerformed
        if (btn_save_runchart.getText().equalsIgnoreCase("Save")) {
            saveRunchart();
        } else {
            updateRunchart();
        }
    }//GEN-LAST:event_btn_save_runchartActionPerformed

    private void btn_emp_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emp_salaryActionPerformed

    }//GEN-LAST:event_btn_emp_salaryActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

    }//GEN-LAST:event_jButton4MouseClicked

    private void btn_branch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_branch1MouseClicked

    }//GEN-LAST:event_btn_branch1MouseClicked

    private void btn_branch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_branch1ActionPerformed
        DisablePanels();
        Chart_Registration_Panel.setVisible(true);
    }//GEN-LAST:event_btn_branch1ActionPerformed

    private void tbl_runchartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_runchartMouseClicked
        searchFromTableValues();
        DisablePanels();
        Chart_Registration_Panel.setVisible(true);
        loadFieldsFromTable();
        btn_save_runchart.setText("Update");
    }//GEN-LAST:event_tbl_runchartMouseClicked

    private void txt_search_runMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search_runMouseClicked
        txt_search_run.setText("");
    }//GEN-LAST:event_txt_search_runMouseClicked

    private void txt_search_runKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_runKeyPressed

    }//GEN-LAST:event_txt_search_runKeyPressed

    private void txt_search_runKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_runKeyReleased
        dtmRunchart.setRowCount(0);
        try {
            List<M_Vehicle> allVehiclesByLetter = vehicleController.getAllVehiclesByLetter(txt_search_run.getText());
            List<T_Runchart> allRuncharts = runchartController.getAllRuncharts();
            for (T_Runchart allRunchart : allRuncharts) {
                for (M_Vehicle m_Vehicle : allVehiclesByLetter) {
                    if (allRunchart.getRunchart_vehicleId().equalsIgnoreCase(m_Vehicle.getVehicle_id())) {
                        String[] roeData = {m_Vehicle.getVehicle_regNo(),allRunchart.getRunchart_date().toString(),allRunchart.getRunchart_description(),allRunchart.getRunchart_timeStart(),allRunchart.getRunchart_timeEnd(),Double.toString(allRunchart.getRunchart_fuelQuantity())};
                        dtmRunchart.addRow(roeData);
                    }
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_search_runKeyReleased

    private void txt_search_runKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_runKeyTyped

    }//GEN-LAST:event_txt_search_runKeyTyped

    private void txt_fuel_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fuel_priceActionPerformed
        fieldFormat.formatDecimalAmount(txt_fuel_price);
        cmb_status.requestFocus();
    }//GEN-LAST:event_txt_fuel_priceActionPerformed

    private void txt_fuel_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fuel_priceKeyPressed
        Validation.priceText(txt_fuel_price);
    }//GEN-LAST:event_txt_fuel_priceKeyPressed

    private void txt_fuel_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fuel_priceKeyReleased
        Validation.priceText(txt_fuel_price);
    }//GEN-LAST:event_txt_fuel_priceKeyReleased

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        fieldFormat.formatDecimalAmount(txt_fuel_price);
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DisablePanels();
        Chart_View_Panel.setVisible(true);
        loadRunchartTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmb_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_vehicleActionPerformed
        if (cmb_vehicle.getSelectedIndex() != 0) {
            try {
                M_Vehicle searchVehicleByNumber = vehicleController.searchVehicleByNumber(cmb_vehicle.getSelectedItem().toString());
                txt_type_of_vehi.setText(vehivleTypeController.searchVehicleType(searchVehicleByNumber.getVehicle_type_id()).getVehicleType_name());
                txt_fuel_type.setText(fuelTypeController.searchFuelType(searchVehicleByNumber.getVehicle_fuelType()).getFuel_name());
            } catch (Exception ex) {
                Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        date_picker_joinDate.requestFocus();
    }//GEN-LAST:event_cmb_vehicleActionPerformed

    private void txt_startKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_startKeyPressed
        Validation.priceText(txt_start);
    }//GEN-LAST:event_txt_startKeyPressed

    private void txt_startKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_startKeyReleased
        Validation.priceText(txt_start);
    }//GEN-LAST:event_txt_startKeyReleased

    private void txt_endKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_endKeyPressed
        Validation.priceText(txt_end);
    }//GEN-LAST:event_txt_endKeyPressed

    private void txt_endKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_endKeyReleased
        Validation.priceText(txt_end);
    }//GEN-LAST:event_txt_endKeyReleased

    private void txt_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_startMouseClicked
        fieldFormat.clearAmountField(txt_start);
    }//GEN-LAST:event_txt_startMouseClicked

    private void txt_endMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_endMouseClicked
        fieldFormat.formatDecimalAmount(txt_start);
        fieldFormat.clearAmountField(txt_end);
    }//GEN-LAST:event_txt_endMouseClicked

    private void spn_start_timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spn_start_timeMouseClicked
        fieldFormat.formatDecimalAmount(txt_end);
        calculateDistance();
    }//GEN-LAST:event_spn_start_timeMouseClicked

    private void txt_fuel_odometerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fuel_odometerMouseClicked
        fieldFormat.clearAmountField(txt_fuel_odometer);
    }//GEN-LAST:event_txt_fuel_odometerMouseClicked

    private void txt_fuel_quantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fuel_quantityMouseClicked
        fieldFormat.formatDecimalAmount(txt_fuel_odometer);
        fieldFormat.clearAmountField(txt_fuel_quantity);
    }//GEN-LAST:event_txt_fuel_quantityMouseClicked

    private void txt_fuel_priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_fuel_priceMouseClicked
        fieldFormat.formatDecimalAmount(txt_fuel_quantity);
        fieldFormat.clearAmountField(txt_fuel_price);
    }//GEN-LAST:event_txt_fuel_priceMouseClicked

    private void cmb_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_statusMouseClicked
        fieldFormat.formatDecimalAmount(txt_fuel_price);
    }//GEN-LAST:event_cmb_statusMouseClicked

    private void txt_distanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_distanceMouseClicked
        calculateDistance();
    }//GEN-LAST:event_txt_distanceMouseClicked

    private void spn_start_timeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spn_start_timeKeyPressed
        fieldFormat.formatDecimalAmount(txt_end);
        calculateDistance();
    }//GEN-LAST:event_spn_start_timeKeyPressed

    private void spn_start_timeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn_start_timeStateChanged
        fieldFormat.formatDecimalAmount(txt_end);
        calculateDistance();
    }//GEN-LAST:event_spn_start_timeStateChanged

    private void spn_start_timePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spn_start_timePropertyChange
        fieldFormat.formatDecimalAmount(txt_end);
        calculateDistance();
    }//GEN-LAST:event_spn_start_timePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Chart_Registration_Panel;
    private javax.swing.JPanel Chart_View_Panel;
    private javax.swing.JPanel bank_panel_hedding3;
    private javax.swing.JPanel bank_panel_hedding5;
    private javax.swing.JButton btn_branch1;
    private javax.swing.JButton btn_emp_new;
    private javax.swing.JButton btn_emp_salary;
    private javax.swing.JButton btn_save_runchart;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JComboBox<String> cmb_vehicle;
    private org.jdesktop.swingx.JXDatePicker date_picker_joinDate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner spn_end_time;
    private javax.swing.JSpinner spn_start_time;
    private javax.swing.JPanel tbl_panel_Branch2;
    private javax.swing.JTable tbl_runchart;
    private javax.swing.JPanel txt_Input_Panel_Branch2;
    private javax.swing.JTextArea txt_desc;
    private javax.swing.JTextField txt_distance;
    private javax.swing.JTextField txt_end;
    private javax.swing.JTextField txt_fuel_odometer;
    private javax.swing.JTextField txt_fuel_price;
    private javax.swing.JTextField txt_fuel_quantity;
    private javax.swing.JTextField txt_fuel_type;
    private javax.swing.JTextField txt_search_run;
    private javax.swing.JTextField txt_start;
    private javax.swing.JTextField txt_type_of_vehi;
    // End of variables declaration//GEN-END:variables

    private void DisablePanels() {
        Chart_Registration_Panel.setVisible(false);
        Chart_View_Panel.setVisible(false);
    }

    private void loadVehicleCombo() {
        cmb_vehicle.removeAll();
        try {
            List<M_Vehicle> allVehicles = vehicleController.getAllVehicles();
            for (M_Vehicle allVehicle : allVehicles) {
                cmb_vehicle.addItem(allVehicle.getVehicle_regNo());
            }
        } catch (Exception ex) {
            Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadRunchartTable() {
        clearFields();
        dtmRunchart.setRowCount(0);
        try {
            List<T_Runchart> allRuncharts = runchartController.getAllRuncharts();
            for (T_Runchart allRunchart : allRuncharts) {
                String[] rowData = {vehicleController.searchVehicle(allRunchart.getRunchart_vehicleId()).getVehicle_regNo(), allRunchart.getRunchart_date().toString(), allRunchart.getRunchart_description(), allRunchart.getRunchart_timeStart(), allRunchart.getRunchart_timeEnd(), Double.toString(allRunchart.getRunchart_fuelQuantity())};
                dtmRunchart.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearFields() {
        cmb_vehicle.setSelectedIndex(0);
        txt_type_of_vehi.setText("");
        txt_fuel_type.setText("");
        date_picker_joinDate.setDate(date);
        txt_desc.setText("");
        txt_start.setText("");
        txt_end.setText("");
        txt_distance.setText("");
        spn_start_time.setEditor(de1);
        spn_end_time.setEditor(de2);
        txt_fuel_odometer.setText("");
        txt_fuel_quantity.setText("");
        txt_fuel_price.setText("");
        cmb_status.setSelectedIndex(0);
        btn_save_runchart.setText("Save");
        cmb_vehicle.requestFocus();
        cmb_vehicle.setEnabled(true);
    }

    private void saveRunchart() {
        try {
            int runchartId = IDGenerator.getNewID("t_runchart", "RUNCHART_ID");
            String vehicleId = vehicleController.searchVehicleByNumber(cmb_vehicle.getSelectedItem().toString()).getVehicle_id();
            Date runDate = date_picker_joinDate.getDate();
            String desc = txt_desc.getText();
            double odoStart = 0;
            if (!"".equals(txt_start.getText())) {
                odoStart = Double.parseDouble(txt_start.getText().replaceAll(",", ""));
            }
            double odoEnd = 0;
            if (!"".equals(txt_end.getText())) {
                odoEnd = Double.parseDouble(txt_end.getText().replaceAll(",", ""));
            }
            String timeStart = de1.getFormat().format(spn_start_time.getValue());
            String timeEnd = de2.getFormat().format(spn_end_time.getValue());
            double fueldoMeter = 0;
            if (!"".equals(txt_fuel_odometer.getText())) {
                fueldoMeter = Double.parseDouble(txt_fuel_odometer.getText().replaceAll(",", ""));
            }
            double fuelQty = 0;
            if (!"".equals(txt_fuel_quantity.getText())) {
                fuelQty = Double.parseDouble(txt_fuel_quantity.getText().replaceAll(",", ""));
            }
            double fuelPrice = 0;
            if (!"".equals(txt_fuel_price.getText())) {
                fuelPrice = Double.parseDouble(txt_fuel_price.getText().replaceAll(",", ""));
            }
            int status = cmb_status.getSelectedIndex();

            T_Runchart runchart = new T_Runchart(runchartId, vehicleId, runDate, desc, odoStart, odoEnd, timeStart, timeEnd, fueldoMeter, fuelQty, fuelPrice, status);
            boolean addRunchart = runchartController.addRunchart(runchart);
            if (addRunchart) {
                JOptionPane.showMessageDialog(this, "New Running Details Successfully Saved..");
                clearFields();
                loadRunchartTable();
            } else {
                JOptionPane.showMessageDialog(this, "Error Occured.. Please Check Again..");
            }

        } catch (Exception ex) {
            Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateRunchart() {
        try {
            int runchartId = runchartGlobal.getRunchart_id();
            String vehicleId = vehicleController.searchVehicleByNumber(cmb_vehicle.getSelectedItem().toString()).getVehicle_id();
            Date runDate = date_picker_joinDate.getDate();
            String desc = txt_desc.getText();
            double odoStart = 0;
            if (!"".equals(txt_start.getText())) {
                odoStart = Double.parseDouble(txt_start.getText().replaceAll(",", ""));
            }
            double odoEnd = 0;
            if (!"".equals(txt_end.getText())) {
                odoEnd = Double.parseDouble(txt_end.getText().replaceAll(",", ""));
            }
            String timeStart = de1.getFormat().format(spn_start_time.getValue());
            String timeEnd = de2.getFormat().format(spn_end_time.getValue());
            double fueldoMeter = 0;
            if (!"".equals(txt_fuel_odometer.getText())) {
                fueldoMeter = Double.parseDouble(txt_fuel_odometer.getText().replaceAll(",", ""));
            }
            double fuelQty = 0;
            if (!"".equals(txt_fuel_quantity.getText())) {
                fuelQty = Double.parseDouble(txt_fuel_quantity.getText().replaceAll(",", ""));
            }
            double fuelPrice = 0;
            if (!"".equals(txt_fuel_price.getText())) {
                fuelPrice = Double.parseDouble(txt_fuel_price.getText().replaceAll(",", ""));
            }
            int status = cmb_status.getSelectedIndex();

            T_Runchart runchart = new T_Runchart(runchartId, vehicleId, runDate, desc, odoStart, odoEnd, timeStart, timeEnd, fueldoMeter, fuelQty, fuelPrice, status);
            boolean updateRunchart = runchartController.updateRunchart(runchart);
            if (updateRunchart) {
                JOptionPane.showMessageDialog(this, "Running Details Successfully Updated..");
                clearFields();
                runchartController.releaseRunchart(runchartId);
                loadRunchartTable();
            } else {
                JOptionPane.showMessageDialog(this, "Error Occured.. Please Check Again..");
            }

        } catch (Exception ex) {
            Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadFieldsFromTable() {
        clearFields();
        try {
            if(runchartController.reserveRunchart(runchartGlobal.getRunchart_id())){
            cmb_vehicle.setSelectedItem(vehicleController.searchVehicle(runchartGlobal.getRunchart_vehicleId()).getVehicle_regNo());
            date_picker_joinDate.setDate(runchartGlobal.getRunchart_date());
            txt_desc.setText(runchartGlobal.getRunchart_description());
            txt_start.setText(decimalFormat.format(runchartGlobal.getRunchart_odoStart()));
            txt_end.setText(decimalFormat.format(runchartGlobal.getRunchart_odoEnd()));
            txt_distance.setText(decimalFormat.format(runchartGlobal.getRunchart_odoEnd() - runchartGlobal.getRunchart_odoStart()));
            spn_start_time.setValue(date);
            spn_end_time.setValue(date);
            txt_fuel_odometer.setText(decimalFormat.format(runchartGlobal.getRunchart_fuelOdoMeter()));
            txt_fuel_quantity.setText(decimalFormat.format(runchartGlobal.getRunchart_fuelQuantity()));
            txt_fuel_price.setText(decimalFormat.format(runchartGlobal.getRunchart_fuelPrice()));
            cmb_status.setSelectedIndex(runchartGlobal.getRunchart_status());
            cmb_vehicle.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(this, "This Run Chart is Using in Another Machine Now.. \n Try Again in a Moment..");
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchFromTableValues() {
        try {

            int selectedRow = tbl_runchart.getSelectedRow();
            String vehicleId = vehicleController.searchVehicleByNumber(dtmRunchart.getValueAt(selectedRow, 0).toString()).getVehicle_id();
            Date runDate = sdf.parse(dtmRunchart.getValueAt(selectedRow, 1).toString());
            String startTime = dtmRunchart.getValueAt(selectedRow, 3).toString();
            String endTime = dtmRunchart.getValueAt(selectedRow, 4).toString();

            runchartGlobal = runchartController.searchRunchart(vehicleId, runDate, startTime, endTime);
            if (runChartIdPub != runchartGlobal.getRunchart_id()) {
                runchartController.releaseRunchart(runChartIdPub);
            }
            runChartIdPub = runchartGlobal.getRunchart_id();

        } catch (Exception ex) {
            Logger.getLogger(Running_Chart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void calculateDistance() {
        double start = 0;
        double end = 0;
        double distance = 0;
        if (!"".equals(txt_start.getText()) && !"".equals(txt_end.getText())) {
            start = Double.parseDouble(txt_start.getText().replaceAll(",", ""));
            end = Double.parseDouble(txt_end.getText().replaceAll(",", ""));
        }
        distance = end - start;
        txt_distance.setText(decimalFormat.format(distance));
    }
}
