/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brotherssoft.samodconstructions.view;

import com.brotherssoft.samodconstructions.controller.M_VehicleController;
import com.brotherssoft.samodconstructions.controller.R_FuelTypeController;
import com.brotherssoft.samodconstructions.controller.R_VehivleTypeController;
import com.brotherssoft.samodconstructions.custom.IDGenerator;
import com.brotherssoft.samodconstructions.model.M_Vehicle;
import com.brotherssoft.samodconstructions.model.R_FuelType;
import com.brotherssoft.samodconstructions.model.R_VehicleType;
import com.brotherssoft.samodconstructions.serverconnector.ServerConnector;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akvasoft
 */
public class Vehical_Registration_Panel extends javax.swing.JPanel {

    R_VehivleTypeController vehivleTypeController;
    R_FuelTypeController fuelTypeController;
    M_VehicleController vehicleController;
    
    DefaultTableModel dtmVehicle;
    
    /**
     * Creates new form Vehical_Registration_Panel
     */
    public Vehical_Registration_Panel() throws Exception {
        initComponents();
        
        vehivleTypeController = ServerConnector.getServerConnetor().getVehivleTypeController();
        fuelTypeController = ServerConnector.getServerConnetor().getFuelTypeController();
        vehicleController = ServerConnector.getServerConnetor().getVehicleController();
        dtmVehicle = (DefaultTableModel) tbl_vehicle_info.getModel();
        
        loadYearCombo();
        loadVehicleTypeCombo();
        loadFuelTypeCombo();
        loadVehicleTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vehical_Registration_Panel = new javax.swing.JPanel();
        user_panel_hedding8 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        bank_panel_input_area5 = new javax.swing.JPanel();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        txt_engine_no = new javax.swing.JTextField();
        btn_save_vehicle = new javax.swing.JButton();
        btn_vehicle_new = new javax.swing.JButton();
        cmb_vehicle_year = new javax.swing.JComboBox<>();
        btn_vehicle_allocation = new javax.swing.JButton();
        jLabel167 = new javax.swing.JLabel();
        cmb_vehicle_type = new javax.swing.JComboBox<>();
        jLabel168 = new javax.swing.JLabel();
        txt_vehi_chasis_no = new javax.swing.JTextField();
        jLabel169 = new javax.swing.JLabel();
        txt_vehicle_amount = new javax.swing.JTextField();
        jLabel170 = new javax.swing.JLabel();
        cmb_vehi_fuel_type = new javax.swing.JComboBox<>();
        jLabel171 = new javax.swing.JLabel();
        txt_vehicle_depriation_rate = new javax.swing.JTextField();
        jLabel172 = new javax.swing.JLabel();
        cmb_vehicle_status = new javax.swing.JComboBox<>();
        jLabel166 = new javax.swing.JLabel();
        txt_vehicle_regNo = new javax.swing.JTextField();
        bank_panel_tbl5 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        tbl_vehicle_info = new javax.swing.JTable();
        txt_search_vehicle = new javax.swing.JTextField();

        Vehical_Registration_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Vehical_Registration_Panel.setPreferredSize(new java.awt.Dimension(1050, 710));

        user_panel_hedding8.setBackground(new java.awt.Color(122, 72, 222));

        jLabel86.setBackground(new java.awt.Color(255, 255, 255));
        jLabel86.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(204, 204, 255));
        jLabel86.setText("Administrations / System Management / Master Details /");

        jLabel87.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(204, 204, 204));
        jLabel87.setText("Vehical Registration");

        javax.swing.GroupLayout user_panel_hedding8Layout = new javax.swing.GroupLayout(user_panel_hedding8);
        user_panel_hedding8.setLayout(user_panel_hedding8Layout);
        user_panel_hedding8Layout.setHorizontalGroup(
            user_panel_hedding8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_panel_hedding8Layout.createSequentialGroup()
                .addGroup(user_panel_hedding8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(user_panel_hedding8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(user_panel_hedding8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel87)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator20)))
                .addContainerGap())
        );
        user_panel_hedding8Layout.setVerticalGroup(
            user_panel_hedding8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_panel_hedding8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel86, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(user_panel_hedding8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel87)
                    .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        bank_panel_input_area5.setBackground(new java.awt.Color(255, 255, 255));
        bank_panel_input_area5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save And Modify Vehicle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel164.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel164.setText("Engine No");

        jLabel165.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel165.setText("Year");

        txt_engine_no.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_engine_no.setToolTipText("");

        btn_save_vehicle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_save_vehicle.setText("Save");
        btn_save_vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_vehicleActionPerformed(evt);
            }
        });

        btn_vehicle_new.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_vehicle_new.setText("New");
        btn_vehicle_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vehicle_newActionPerformed(evt);
            }
        });

        cmb_vehicle_year.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_vehicle_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Year -" }));

        btn_vehicle_allocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_vehicle_allocation.setText("Vehicle Allocation");
        btn_vehicle_allocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vehicle_allocationMouseClicked(evt);
            }
        });

        jLabel167.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel167.setText("Type");

        cmb_vehicle_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_vehicle_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Vehicle Type -" }));

        jLabel168.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel168.setText("Chasis No");

        txt_vehi_chasis_no.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel169.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel169.setText("Amount");

        txt_vehicle_amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel170.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel170.setText("Fuel Type");

        cmb_vehi_fuel_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_vehi_fuel_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Select Fuel Type -" }));

        jLabel171.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel171.setText("Depriciation Rate");

        txt_vehicle_depriation_rate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel172.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel172.setText("Status");

        cmb_vehicle_status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_vehicle_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        jLabel166.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel166.setText("Registration No");

        txt_vehicle_regNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_vehicle_regNo.setToolTipText("");

        javax.swing.GroupLayout bank_panel_input_area5Layout = new javax.swing.GroupLayout(bank_panel_input_area5);
        bank_panel_input_area5.setLayout(bank_panel_input_area5Layout);
        bank_panel_input_area5Layout.setHorizontalGroup(
            bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel164, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_engine_no))
                    .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel165, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_vehicle_year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_input_area5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_vehicle_allocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_vehicle_new, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel167, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_vehicle_type, 0, 326, Short.MAX_VALUE))
                    .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel168, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_vehi_chasis_no))
                    .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel169, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_vehicle_amount))
                    .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel170, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_vehi_fuel_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel171, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_vehicle_depriation_rate))
                    .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel172, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_vehicle_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                        .addComponent(jLabel166, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_vehicle_regNo)))
                .addContainerGap())
        );
        bank_panel_input_area5Layout.setVerticalGroup(
            bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panel_input_area5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel167, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_vehicle_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel166, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vehicle_regNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel164, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_engine_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel168, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vehi_chasis_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel165, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_vehicle_year))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel169, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vehicle_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel170, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_vehi_fuel_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel171, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vehicle_depriation_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel172, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_vehicle_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bank_panel_input_area5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vehicle_new, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vehicle_allocation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bank_panel_tbl5.setBackground(new java.awt.Color(255, 255, 255));
        bank_panel_tbl5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle Infomation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        tbl_vehicle_info.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbl_vehicle_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Vehicle Registration Number"
            }
        ));
        tbl_vehicle_info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_vehicle_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_vehicle_infoMouseClicked(evt);
            }
        });
        jScrollPane21.setViewportView(tbl_vehicle_info);

        txt_search_vehicle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_search_vehicle.setForeground(new java.awt.Color(102, 102, 102));
        txt_search_vehicle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_search_vehicle.setText("Search Vehicle");
        txt_search_vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search_vehicleMouseClicked(evt);
            }
        });
        txt_search_vehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_vehicleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout bank_panel_tbl5Layout = new javax.swing.GroupLayout(bank_panel_tbl5);
        bank_panel_tbl5.setLayout(bank_panel_tbl5Layout);
        bank_panel_tbl5Layout.setHorizontalGroup(
            bank_panel_tbl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_tbl5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bank_panel_tbl5Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(txt_search_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bank_panel_tbl5Layout.setVerticalGroup(
            bank_panel_tbl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panel_tbl5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_search_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout Vehical_Registration_PanelLayout = new javax.swing.GroupLayout(Vehical_Registration_Panel);
        Vehical_Registration_Panel.setLayout(Vehical_Registration_PanelLayout);
        Vehical_Registration_PanelLayout.setHorizontalGroup(
            Vehical_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vehical_Registration_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bank_panel_input_area5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bank_panel_tbl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(user_panel_hedding8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Vehical_Registration_PanelLayout.setVerticalGroup(
            Vehical_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vehical_Registration_PanelLayout.createSequentialGroup()
                .addComponent(user_panel_hedding8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Vehical_Registration_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bank_panel_input_area5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bank_panel_tbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vehical_Registration_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vehical_Registration_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_vehicle_allocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vehicle_allocationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vehicle_allocationMouseClicked

    private void btn_save_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_vehicleActionPerformed
        if(btn_save_vehicle.getText().equalsIgnoreCase("Save")){
            saveVehicle();
        }else{
            updateVehicle();
        }
    }//GEN-LAST:event_btn_save_vehicleActionPerformed

    private void tbl_vehicle_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_vehicle_infoMouseClicked
        loadFromVehicleTable();
        txt_search_vehicle.setText("Search Vehicle");
        txt_search_vehicle.setForeground(Color.GRAY);
    }//GEN-LAST:event_tbl_vehicle_infoMouseClicked

    private void btn_vehicle_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vehicle_newActionPerformed
        
        cmb_vehicle_type.setSelectedIndex(0);
        txt_vehicle_regNo.setText("");
        txt_engine_no.setText("");
        txt_vehi_chasis_no.setText("");
        cmb_vehicle_year.setSelectedIndex(0);
        txt_vehicle_amount.setText("");
        cmb_vehi_fuel_type.setSelectedIndex(0);
        txt_vehicle_depriation_rate.setText("");
        cmb_vehicle_status.setSelectedIndex(0);
        
        btn_save_vehicle.setText("Save");
        
    }//GEN-LAST:event_btn_vehicle_newActionPerformed

    private void txt_search_vehicleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_vehicleKeyReleased
        try {
            
            dtmVehicle.setRowCount(0);
            List<M_Vehicle> allVehicles = vehicleController.getAllVehiclesByLetter(txt_search_vehicle.getText());
            for (M_Vehicle allVehicle : allVehicles) {
                String[] rowData = {allVehicle.getVehicle_regNo()};
                dtmVehicle.addRow(rowData);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Vehical_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_search_vehicleKeyReleased

    private void txt_search_vehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search_vehicleMouseClicked
        txt_search_vehicle.setText("");
        txt_search_vehicle.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_search_vehicleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Vehical_Registration_Panel;
    private javax.swing.JPanel bank_panel_input_area5;
    private javax.swing.JPanel bank_panel_tbl5;
    private javax.swing.JButton btn_save_vehicle;
    private javax.swing.JButton btn_vehicle_allocation;
    private javax.swing.JButton btn_vehicle_new;
    private javax.swing.JComboBox<String> cmb_vehi_fuel_type;
    private javax.swing.JComboBox<String> cmb_vehicle_status;
    private javax.swing.JComboBox<String> cmb_vehicle_type;
    private javax.swing.JComboBox<String> cmb_vehicle_year;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JTable tbl_vehicle_info;
    private javax.swing.JTextField txt_engine_no;
    private javax.swing.JTextField txt_search_vehicle;
    private javax.swing.JTextField txt_vehi_chasis_no;
    private javax.swing.JTextField txt_vehicle_amount;
    private javax.swing.JTextField txt_vehicle_depriation_rate;
    private javax.swing.JTextField txt_vehicle_regNo;
    private javax.swing.JPanel user_panel_hedding8;
    // End of variables declaration//GEN-END:variables

    private void loadYearCombo() {
        
        ArrayList<String> years = new ArrayList<>();
        for (int i = 1950; i <= Calendar.getInstance().get(Calendar.YEAR); i++) {
            years.add(i+"");
        }
        cmb_vehicle_year.removeAll();
        for (String year : years) {
            cmb_vehicle_year.addItem(year);
        }
        
    }

    private void loadVehicleTypeCombo() {
        try {
            
            List<R_VehicleType> allVehicleTypes = vehivleTypeController.getAllVehicleTypes();
            cmb_vehicle_type.removeAll();
            for (R_VehicleType allVehicleType : allVehicleTypes) {
                cmb_vehicle_type.addItem(allVehicleType.getVehicleType_name());
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Vehical_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadFuelTypeCombo() {
        try {
            
            List<R_FuelType> allFuelTypes = fuelTypeController.getAllFuelTypes();
            cmb_vehi_fuel_type.removeAll();
            for (R_FuelType allFuelType : allFuelTypes) {
                cmb_vehi_fuel_type.addItem(allFuelType.getFuel_name());
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Vehical_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadVehicleTable() {
        try {
            
            dtmVehicle.setRowCount(0);
            List<M_Vehicle> allVehicles = vehicleController.getAllVehicles();
            for (M_Vehicle allVehicle : allVehicles) {
                String[] rowData = {allVehicle.getVehicle_regNo()};
                dtmVehicle.addRow(rowData);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Vehical_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveVehicle() {
        try {
            
            int vehicleId = IDGenerator.getNewID("m_vehicle", "VEHICLE_ID");
            String regNo = txt_vehicle_regNo.getText();
            int vehicleTypeId = vehivleTypeController.searchVehicleType(cmb_vehicle_type.getSelectedItem().toString()).getVehicleType_id();
            String engineNo = txt_engine_no.getText();
            String chasisNo = txt_vehi_chasis_no.getText();
            String year = cmb_vehicle_year.getSelectedItem().toString();
            double amount = Double.parseDouble(txt_vehicle_amount.getText());
            double depriationRate = Double.parseDouble(txt_vehicle_depriation_rate.getText());
            String status = null;
                if(cmb_vehicle_status.getSelectedIndex() == 0){
                    status = "A";
                }else{
                    status = "I";
                }
            int fuelTypeId = fuelTypeController.searchFuelType(cmb_vehi_fuel_type.getSelectedItem().toString()).getFuel_id();
            String vehicleAllocationStatus = "";
            
            M_Vehicle vehicle = new M_Vehicle(vehicleId, regNo, vehicleTypeId, engineNo, chasisNo, year, amount, depriationRate, status, fuelTypeId, vehicleAllocationStatus);
            boolean addVehivle = vehicleController.addVehivle(vehicle);
            if (addVehivle) {
                JOptionPane.showMessageDialog(this, "Vehicle Added Succesfully..");
            }else{
                JOptionPane.showMessageDialog(this, "Vehicle Adding Failed");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Vehical_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        loadVehicleTable();
    }

    private void loadFromVehicleTable() {            
        try {
            
            M_Vehicle vehicle = getSelectedVehicleNoFromTable();
            cmb_vehicle_type.setSelectedItem(vehivleTypeController.searchVehicleType(vehicle.getVehicle_type_id()).getVehicleType_name());
            txt_vehicle_regNo.setText(vehicle.getVehicle_regNo());
            txt_engine_no.setText(vehicle.getVehicle_engineNo());
            txt_vehi_chasis_no.setText(vehicle.getVehicle_chasisNo());
            cmb_vehicle_year.setSelectedItem(vehicle.getVehicle_year());
            txt_vehicle_amount.setText(Double.toString(vehicle.getVehicle_amount()));
            cmb_vehi_fuel_type.setSelectedItem(fuelTypeController.searchFuelType(vehicle.getVehicle_fuelType()).getFuel_name());
            txt_vehicle_depriation_rate.setText(Double.toString(vehicle.getVehicle_depreciationRate()));
            if(vehicle.getVehicle_status().equalsIgnoreCase("A")){
                cmb_vehicle_status.setSelectedIndex(0);
            }else{
                cmb_vehicle_status.setSelectedIndex(1);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Vehical_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        btn_save_vehicle.setText("Update");
               
    }

    private M_Vehicle getSelectedVehicleNoFromTable() {
        M_Vehicle searchVehicle = null;
        try {
            
            int selectedRow = tbl_vehicle_info.getSelectedRow();
            String vehicleNo = dtmVehicle.getValueAt(selectedRow, 0).toString();
            searchVehicle = vehicleController.searchVehicle(vehicleNo);
            
            
        } catch (Exception ex) {
            Logger.getLogger(Vehical_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return searchVehicle;
    }

    private void updateVehicle() {
        try {
            
            int vehicleId = getSelectedVehicleNoFromTable().getVehicle_id();
            String regNo = txt_vehicle_regNo.getText();
            int vehicleTypeId = vehivleTypeController.searchVehicleType(cmb_vehicle_type.getSelectedItem().toString()).getVehicleType_id();
            String engineNo = txt_engine_no.getText();
            String chasisNo = txt_vehi_chasis_no.getText();
            String year = cmb_vehicle_year.getSelectedItem().toString();
            double amount = Double.parseDouble(txt_vehicle_amount.getText());
            double depriationRate = Double.parseDouble(txt_vehicle_depriation_rate.getText());
            String status = null;
            if(cmb_vehicle_status.getSelectedIndex() == 0){
                status = "A";
            }else{
                status = "I";
            }
            int fuelTypeId = fuelTypeController.searchFuelType(cmb_vehi_fuel_type.getSelectedItem().toString()).getFuel_id();
            String vehicleAllocationStatus = "";
            
            M_Vehicle vehicle = new M_Vehicle(vehicleId, regNo, vehicleTypeId, engineNo, chasisNo, year, amount, depriationRate, status, fuelTypeId, vehicleAllocationStatus);
            boolean updateVehicle = vehicleController.updateVehicle(vehicle);
            if (updateVehicle) {
                JOptionPane.showMessageDialog(this, "Vehicle Details Updated Successfully..");
            }else{
                JOptionPane.showMessageDialog(this, "Vehicle Detail Updating Failed..");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Vehical_Registration_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        loadVehicleTable();
    }
}
